Module_IrcTracker: Erebot\Module\IrcTracker Class Reference
Erebot\Module\IrcTracker Class Reference
A module that keeps track of users which are on the same IRC channels as the bot.
Public Member Functions
byChannelModes ($chan, $modes, $negate=false)
getCommonChans ($nick)
getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event,\Erebot\Interfaces\TextWrapper $words)
getInfo ($token, $info, $args=array())
handleCapabilities (\Erebot\Interfaces\EventHandler $handler,\Erebot\Event\ServerCapabilities $event)
handleChanModeAddition (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\ChanModeGiven $event)
handleChanModeRemoval (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\ChanModeTaken $event)
handleJoin (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Join $event)
handleLeaving (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\Generic $event)
handleNames (\Erebot\Interfaces\NumericHandler $handler,\Erebot\Interfaces\Event\Numeric $numeric)
handleNick (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Nick $event)
handleNotification (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\Source $event)
handleWho (\Erebot\Interfaces\NumericHandler $handler,\Erebot\Interfaces\Event\Numeric $numeric)
IAL ($mask, $chan=null)
isOn ($chan, $nick=null)
reload ($flags)
removeUser (\Erebot\TimerInterface $timer, $nick)
startTracking ($nick, $cls= '\\Erebot\\Module\\IrcTracker\\Token')
userPrivileges ($chan, $nick)
Static Public Member Functions
static extractNick ($source)
Public Attributes
const INFO_HOST = 'Host'
Return the current hostname for some user.
const INFO_IDENT = 'Ident'
Return the current identity (in the IRC sense) for some user.
const INFO_ISON = 'IsOn'
Return whether the given user is currently connected or not.
const INFO_MASK = 'Mask'
Return the current IRC mask for some user.
const INFO_NICK = 'Nick'
Return the current nickname for some user.
Protected Member Functions
realRemoveUser ($nick)
unload ()
updateUser ($nick, $ident, $host)
Protected Attributes
$chans
Maps channels to a list of tokens for users present in that channel.
$hasUHNAMES
Whether the IRC server supports the UHNAMES extension or not.
$ial
Internal Address List, à la mIRC.
$nicks
Maps tokens to normalized nicknames.
$sequence
Sequence number, incremented by 1 after each new token generation.
Detailed Description
A module that keeps track of users which are on the same IRC channels as the bot.
Definition at line 26 of file IrcTracker.php.
Member Function Documentation
Erebot\Module\IrcTracker::byChannelModes ($chan, $modes, $negate = false)
Returns a list with the nicknames of all users that (do not) have some specific modes on them on some IRC channel.
Parameters
string $chan The IRC channel we're interested in.
array $modes Only return those users that have these statuses on the given IRC channel.
bool $negate Negate the search, ie. only return those users that DO NOT have the given statuses on the given IRC channel.
Return values
list Nicknames of all users matching the given criteria.
Exceptions
Erebot::NotFoundException The bot is not present on the given IRC channel and so the search cannot succeed.
Definition at line 1007 of file IrcTracker.php.
static Erebot\Module\IrcTracker::extractNick ($source) static
Given some user's full IRC identity (nick!ident@host), this methods extracts and returns that user's nickname.
Parameters
string $source Some user's full IRC identity (as "nick!ident\@host").
Return values
string The nickname of the user represented by that identity.
Note
This method will still work as expected if given only a nickname to work with. Therefore, it is safe to call this method with the result of a previous invocation. Thus, the following snippet: Erebot::Module::IrcTracker::extractNick(Erebot::Module::IrcTracker::extractNick('foo!bar@baz')); will return "foo" as expected.
Definition at line 229 of file IrcTracker.php.
Erebot\Module\IrcTracker::getCommonChans ($nick)
Returns a list of IRC channels the bot and some other user have in common.
Parameters
string $nick Nickname of the user for which we want to know what channels (s)he shares with the bot.
Return values
list A list with the names of all IRC channels that user and the bot have in common.
Exceptions
Erebot::NotFoundException The given nickname does not match any known user.
Definition at line 863 of file IrcTracker.php.
Referenced by Erebot\Module\IrcTracker\handleLeaving(), and Erebot\Module\IrcTracker\realRemoveUser().
Erebot\Module\IrcTracker::getInfo ($token, $info, $args = array())
Returns information about some user given a token associated with that user.
Parameters
opaque $token Token associated with the user.
opaque $info The type of information we're interested in. This is one of the INFO_* constants provided by this class.
array $args (optional) Additional arguments for the query. Defaults to an empty array. At present time, this argument is only useful when you pass one of Erebot::Module::IrcTracker::INFO_HOST or Erebot::Module::IrcTracker::INFO_MASK as the value for $info. In this case, you may pass an array containing a boolean ($canonical) indicating the type of hostname canonicalization to apply. See also Erebot::Interfaces::Identity::getHost() for more information on the $canonical parameter.
Return values
mixed Requested information about that user. This may be null if the requested information has not been obtained yet.
Exceptions
Erebot::InvalidValueException The value for $info is invalid.
Erebot::NotFoundException The given $token does not match any known user.
Warning
This method is not meant to be called directly. Instead, you should call the equivalent methods (getNick(), getHost(), etc.) from the token returned by Erebot::Module::IrcTracker::startTracking().
Definition at line 761 of file IrcTracker.php.
Erebot\Module\IrcTracker::handleCapabilities (\Erebot\Interfaces\EventHandler $handler, \Erebot\Event\ServerCapabilities $event)
Handles server capabilities.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Event::ServerCapabilities $event An event referencing a module that can determine the IRC server's capabilities, such as Erebot::Module::ServerCapabilities.
(PHPMD.UnusedFormalParameter)
Definition at line 470 of file IrcTracker.php.
Erebot\Module\IrcTracker::handleChanModeAddition (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\ChanModeGiven $event)
Handles someone receiving a new status on an IRC channel, for example, when someone is OPped.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::ChanModeGiven $event Event indicating someone's status changed on an IRC channel the bot is currently on, giving that person new privileges.
(PHPMD.UnusedFormalParameter)
Definition at line 617 of file IrcTracker.php.
Erebot\Module\IrcTracker::handleChanModeRemoval (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\ChanModeTaken $event)
Handles someone losing his status on an IRC channel, for example, when someone is DEOPped.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::ChanModeTaken $event Event indicating someone's status changed on an IRC channel the bot is currently on, removing privileges from that person.
(PHPMD.UnusedFormalParameter)
Definition at line 648 of file IrcTracker.php.
Erebot\Module\IrcTracker::handleJoin (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Join $event)
Handles some user joining an IRC channel the bot is currently on.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Join $event Event indicating that some user joined a channel the bot is on.
(PHPMD.UnusedFormalParameter)
Definition at line 585 of file IrcTracker.php.
References Erebot\Module\IrcTracker\updateUser().
Erebot\Module\IrcTracker::handleLeaving (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\Generic $event)
Handles some user leaving an IRC channel. This may result from either a QUIT or KICK command.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::Generic $event An event indicating that some user is leaving an IRC channel the bot is on.
(PHPMD.UnusedFormalParameter)
Definition at line 411 of file IrcTracker.php.
References Erebot\Module\IrcTracker\getCommonChans(), and Erebot\Module\IrcTracker\realRemoveUser().
Erebot\Module\IrcTracker::handleNames (\Erebot\Interfaces\NumericHandler $handler, \Erebot\Interfaces\Event\Numeric $numeric)
Handles a list with the nicknames of all users in a given IRC channel.
Parameters
Erebot::Interfaces::NumericHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Numeric $numeric A numeric event with the nicknames of users in an IRC channel the bot just joined. This is the same type of numeric event as when the NAMES command is issued.
(PHPMD.UnusedFormalParameter)
Definition at line 499 of file IrcTracker.php.
References Erebot\Module\IrcTracker\updateUser().
Erebot\Module\IrcTracker::handleNick (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Nick $event)
Handles a nick change.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Nick $event Nick change event.
(PHPMD.UnusedFormalParameter)
Definition at line 378 of file IrcTracker.php.
References Erebot\Module\IrcTracker\realRemoveUser().
Erebot\Module\IrcTracker::handleNotification (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\Source $event)
Handles a notification about some user (dis)connecting from/to the IRC network.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::Source $event Notification.
(PHPMD.UnusedFormalParameter)
Definition at line 349 of file IrcTracker.php.
References Erebot\Module\IrcTracker\realRemoveUser(), and Erebot\Module\IrcTracker\updateUser().
Erebot\Module\IrcTracker::handleWho (\Erebot\Interfaces\NumericHandler $handler, \Erebot\Interfaces\Event\Numeric $numeric)
Handles information about some user.
Parameters
Erebot::Interfaces::NumericHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Numeric $numeric Numeric event containing some user's nickname, IRC identity and hostname.
(PHPMD.UnusedFormalParameter)
Definition at line 564 of file IrcTracker.php.
References Erebot\Module\IrcTracker\updateUser().
Erebot\Module\IrcTracker::IAL ($mask, $chan = null)
Returns a list with the masks of all users that match a given (wildcard) mask and are on the given IRC channel.
Parameters
string $mask A wildcard match to use to filter out users (eg. "*!*@*.fr" to find all users connected using a french ISP).
mixed $chan (optional) Only search for users that have joined this IRC channel (given by its name, as a string). May also be set to null to search for all users known to the bot, no matter what channels they are currently on. Defaults to null.
Return values
list A list with the masks of all users matching the given criteria.
Exceptions
Erebot::NotFoundException The given channel name does not match the name of any channel the bot is on.
Definition at line 909 of file IrcTracker.php.
Erebot\Module\IrcTracker::isOn ($chan, $nick = null)
Indicates whether some user is present on a given IRC channel.
Parameters
string $chan IRC channel that user must be on.
mixed $nick (optional) Either some user's nickname (a string) or null. Defaults to null. When this parameter is null, this method tests whether the bot is on the given IRC channel or not.
Return values
bool true is the given user is on that IRC channel, false otherwise.
Definition at line 832 of file IrcTracker.php.
Erebot\Module\IrcTracker::realRemoveUser ($nick) protected
Removes some user from the IAL.
Parameters
string $nick Nickname of the user that is to be removed from the IAL.
Definition at line 301 of file IrcTracker.php.
References Erebot\Module\IrcTracker\getCommonChans().
Referenced by Erebot\Module\IrcTracker\handleLeaving(), Erebot\Module\IrcTracker\handleNick(), Erebot\Module\IrcTracker\handleNotification(), and Erebot\Module\IrcTracker\removeUser().
Erebot\Module\IrcTracker::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 72 of file IrcTracker.php.
Erebot\Module\IrcTracker::removeUser (\Erebot\TimerInterface $timer, $nick)
Removes some user from the IAL when the timer associated with their disconnection times out.
Parameters
Erebot::TimerInterface $timer Timer associated with the user's disconnection.
string $nick Nickname of the user to remove from the IAL.
(PHPMD.UnusedFormalParameter)
Definition at line 332 of file IrcTracker.php.
References Erebot\Module\IrcTracker\realRemoveUser().
Erebot\Module\IrcTracker::startTracking ($nick, $cls = '\\Erebot\\Module\\IrcTracker\\Token')
Returns a tracking token for some user.
Parameters
string $nick The nickname of some user we want to start tracking.
string $cls (optional) Class to use to create the token. Defaults to Erebot::Module::IrcTracker::Token.
Return values
mixed A token that can later be used to return information on that user (such as his/her nickname, IRC identity, hostname and whether that person is still online or not).
Exceptions
Erebot::NotFoundException There is currently no user connected on an IRC channel the bot is on matching the given nickname.
Erebot::InvalidValueException The given nick is invalid.
Definition at line 695 of file IrcTracker.php.
Erebot\Module\IrcTracker::unload () protected
Frees the resources associated with this module.
Definition at line 173 of file IrcTracker.php.
Erebot\Module\IrcTracker::updateUser ($nick, $ident, $host) protected
Updates the IAL with new information on some user.
Parameters
string $nick Some user's nickname whose IAL entry will be updated.
string $ident Some user's identity, in the IRC sense of the term.
string $host Some user's hostname.
Definition at line 250 of file IrcTracker.php.
Referenced by Erebot\Module\IrcTracker\handleJoin(), Erebot\Module\IrcTracker\handleNames(), Erebot\Module\IrcTracker\handleNotification(), and Erebot\Module\IrcTracker\handleWho().
Erebot\Module\IrcTracker::userPrivileges ($chan, $nick)
Returns channel status associated with the given user.
Parameters
string $chan The IRC channel we're interested in.
string $nick Nickname of the user whose status on the given channel we're interested in.
Return values
list A list with the status/privileges for that user on the given channel. Each status is given by the letter for the channel mode that refers to it (eg. "o" for "operator status").
Exceptions
Erebot::NotFoundException The given channel or nickname is not not known to the bot.
Definition at line 974 of file IrcTracker.php.
The documentation for this class was generated from the following file:
src/IrcTracker.php