Module_WatchList: Erebot\Module\WatchList Class Reference
Erebot\Module\WatchList Class Reference
A module that can be used to manage the bot's IRC WATCH list.
Public Member Functions
getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event,\Erebot\Interfaces\TextWrapper $words)
handleCapabilities (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ServerCapabilities $event)
handleConnect (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Connect $event)
handleISON (\Erebot\Interfaces\NumericHandler $handler,\Erebot\Interfaces\Event\Numeric $numeric)
reload ($flags)
sendRequest (\Erebot\TimerInterface $timer)
Protected Member Functions
splitNicks ()
Protected Attributes
$pending
Number of nicks sent in an ISON command and avaiting a response.
$timer
A timer used to emulate the WATCH command using the ISON command.
$watchedNicks
List of nicknames currently being followed by this module.
Detailed Description
A module that can be used to manage the bot's IRC WATCH list.
This module adds support for the WATCH/ISON commands to Erebot. It can be used to monitor (dis)connections of some IRC users.
Attention
The WATCH command is an extension to the official IRC protocol and is supported only by some IRC networks. Most IRC servers that implement it have strict restrictions on the number of users someone may track using this command. The ISON command however is safe (and is part of the official IRC protocol). If you plan to track a lot of users, don't use this module.
Note
In the future, this module may use the most appropriate command to monitor (dis)connections, depending on the number of nicks it has to track.
Definition at line 42 of file WatchList.php.
Member Function Documentation
Erebot\Module\WatchList::getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event, \Erebot\Interfaces\TextWrapper $words)
Provides help about this module.
Parameters
Erebot::Interfaces::Event::Base::TextMessage $event Some help request.
Erebot::Interfaces::TextWrapper $words Parameters passed with the request. This is the same as this module's name when help is requested on the module itself (in opposition with help on a specific command provided by the module).
Definition at line 130 of file WatchList.php.
Erebot\Module\WatchList::handleCapabilities (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ServerCapabilities $event)
Upon connection, requests that the server send notifications for (dis)connection related to IRC nicknames this modules is currently following.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::ServerCapabilities $event Event containing information on server capabilities.
(PHPMD.UnusedFormalParameter)
Definition at line 183 of file WatchList.php.
Erebot\Module\WatchList::handleConnect (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Connect $event)
Upon connection, requests that the server send notifications for (dis)connection related to IRC nicknames this modules is currently following.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Connect $event Connection event.
(PHPMD.UnusedFormalParameter)
Definition at line 206 of file WatchList.php.
References Erebot\Module\WatchList\$watchedNicks, Erebot\Module\WatchList\sendRequest(), and Erebot\Module\WatchList\splitNicks().
Erebot\Module\WatchList::handleISON (\Erebot\Interfaces\NumericHandler $handler, \Erebot\Interfaces\Event\Numeric $numeric)
Handle the response to an ISON command.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Numeric $numeric ISON response.
(PHPMD.UnusedFormalParameter)
Definition at line 246 of file WatchList.php.
References Erebot\Module\WatchList\$pending, and Erebot\Module\WatchList\splitNicks().
Erebot\Module\WatchList::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 65 of file WatchList.php.
References Erebot\Module\WatchList\$watchedNicks.
Erebot\Module\WatchList::sendRequest (\Erebot\TimerInterface $timer)
Send ISON requests to see whether users in the WATCH list recently logged on/off.
Parameters
Erebot::TimerInterface $timer The (periodic) timer that triggered the request.
(PHPMD.UnusedFormalParameter)
Definition at line 315 of file WatchList.php.
References Erebot\Module\WatchList\splitNicks().
Referenced by Erebot\Module\WatchList\handleConnect().
Erebot\Module\WatchList::splitNicks () protected
Return a list of strings made of the nicknames being tracked by this watch list.
Each string is built so that it can be sent to the IRC server without being truncated.
Return values
array List of strings containing tracked nicknames, separated by spaces.
Definition at line 163 of file WatchList.php.
Referenced by Erebot\Module\WatchList\handleConnect(), Erebot\Module\WatchList\handleISON(), and Erebot\Module\WatchList\sendRequest().
The documentation for this class was generated from the following file:
src/WatchList.php