language: php
sudo: false
dist: xenial
git:
  submodules: false

addons:
  apt:
    update: false
    packages:
      - python-sphinx
      - python-babel
      - doxygen
      - graphviz
      - ghostscript
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-lang-french
      - texlive-lang-english

branches:
  only:
  - build

notifications:
  email: false

php:
  - 7.1

env:
  - MODULE=Erebot/Erebot
  - MODULE=Erebot/Module_AZ
  - MODULE=Erebot/Module_Admin
  - MODULE=Erebot/Module_AutoConnect
  - MODULE=Erebot/Module_AutoIdent
  - MODULE=Erebot/Module_AutoJoin

before_script:
  - phpenv config-rm xdebug.ini
  - composer require erebot/buildenv

script:
  - export BRANCH_NAME="build-${MODULE/\//-}"
  - ./travis.sh $MODULE $BRANCH_NAME

deploy:
  local-dir: tmp/output
  provider: pages
  target-branch: $BRANCH_NAME
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  # Setting keep-history to true makes it easier
  # to track the contents of the master branch.
  keep-history: true
  verbose: true
  on:
    all_branches: true
    condition: '-e ".deploy"'

jobs:
  include:
    - stage: deploy
      name: "Publication"
      script:
        - git submodule update --init --remote
        - find staging -mindepth 3 -maxdepth 3 -type d -name .git -exec rm -rf '{}' '+'
      deploy:
        local-dir: staging
        provider: pages
        target-branch: master
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        # Setting keep-history to true makes it easier
        # to track the contents of the master branch.
        keep-history: true
        verbose: true
        on:
          all_branches: true
