language: php
sudo: false
dist: xenial

addons:
  apt:
    #update: true
    packages:
      - python-sphinx
      - python-babel
      - doxygen
      - graphviz
      - ghostscript
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-lang-french
      - texlive-lang-english

env:
    DO_NOT_DEPLOY: "1"

notifications:
  email: false

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - composer require erebot/buildenv

script:
  - export DO_NOT_DEPLOY="$(./travis.sh >&2; echo $?)"
  - echo "Do not deploy? $DO_NOT_DEPLOY"

deploy:
  local-dir: tmp/output
  provider: pages
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    all_branches: true
    condition: '"$DO_NOT_DEPLOY" -eq 0'
