Erebot: Erebot\Proxy\SOCKS Class Reference
Erebot\Proxy\SOCKS Class Reference
Proxies data through a SOCKS 5 proxy.
Public Member Functions
proxify (\Erebot\URIInterface $proxyURI,\Erebot\URIInterface $nextURI)
Protected Member Functions
read ($len)
userpass (\Erebot\URIInterface $proxyURI)
write ($line)
Detailed Description
Proxies data through a SOCKS 5 proxy.
Definition at line 27 of file SOCKS.php.
Member Function Documentation
Erebot\Proxy\SOCKS::read ($len) protected
Reads some data from the proxy server.
Parameters
int $len Number of bytes to read from the proxy server.
Return values
string Actual data read.
Definition at line 201 of file SOCKS.php.
Referenced by Erebot\Proxy\SOCKS\userpass().
Erebot\Proxy\SOCKS::userpass (\Erebot\URIInterface $proxyURI) protected
Does the authentication step.
Parameters
Erebot::URIInterface $proxyURI An object representing the URI of this SOCKS proxy server, containing the credentials that will be sent during the authentication step.
Definition at line 123 of file SOCKS.php.
References Erebot\Proxy\SOCKS\read(), and Erebot\Proxy\SOCKS\write().
Erebot\Proxy\SOCKS::write ($line) protected
Passes some data to the proxy server.
Parameters
string $line Data to send.
Return values
int Number of bytes actually sent (this may be lower that the length of the initial $line if some bytes could not be sent).
Definition at line 181 of file SOCKS.php.
Referenced by Erebot\Proxy\SOCKS\userpass().
The documentation for this class was generated from the following file:
src/Proxy/SOCKS.php