Module_Wordlists: Erebot\Module\Wordlists\Wordlist Class Reference
Erebot\Module\Wordlists\Wordlist Class Reference
Represents a list of words that can be iterated.
Public Member Functions
__construct (\Erebot\Module\Wordlists $module, $name, $file)
__destruct ()
count ()
findWord ($word)
free ()
getCollator ()
getMetadata ($type)
offsetExists ($word)
offsetGet ($offset)
Public Member Functions inherited from Erebot\Module\Wordlists\Base
offsetSet ($offset, $value)
offsetUnset ($offset)
Public Attributes
const METADATA_AUTHORS = 'author'
A list with the names (and optionally emails) of this list's authors.
const METADATA_DESCRIPTION = 'description'
A short description of the content of this list.
const METADATA_FILE = 'file'
Path to the list's file.
const METADATA_KEYWORDS = 'keyword'
A list of keywords associated with this list.
const METADATA_LICENCE = 'license'
Information on the license for this list of words.
const METADATA_LICENSE = 'license'
Information on the license for this list of words.
const METADATA_LOCALE = 'locale'
The locale used by the words, using the ICU format (mandatory).
const METADATA_NAME = 'name'
Name of the list (same as the filename with extension removed).
const METADATA_URL = 'url'
A URL where more information/resources for this list may be found.
const METADATA_VERSION = 'version'
Version of the list.
Public Attributes inherited from Erebot\Module\Wordlists\Base
const WORD_FILTER
Pattern used to recognize (composed) "words".
Protected Member Functions
parseFile ($file)
Protected Attributes
$collator
A collator compatible with this wordlist.
$countQuery
An SQL query that returns the number of words in this wordlist.
$db
Database link as a PDO handle.
$existsQuery
An SQL query to test whether some word is present in the list or not.
$file
Path to the file where this wordlists is stored.
$getQuery
An SQL query to return the word at a given offset.
$metadata
Metadata associated with this list.
$module
Instance of Erebot::Module::Wordlists this wordlist is associated with.
$name
Name of this wordlist.
Additional Inherited Members
Static Public Member Functions inherited from Erebot\Module\Wordlists\Base
static isWord ($word)
Detailed Description
Represents a list of words that can be iterated.
Note
Wordlists are read-only objects. Any attempt to change their content will result in an exception being thrown.
Definition at line 29 of file Wordlist.php.
Constructor & Destructor Documentation
Erebot\Module\Wordlists\Wordlist::__construct (\Erebot\Module\Wordlists $module, $name, $file)
Constructs a new wordlist.
Parameters
Erebot::Module::Wordlists $module A reference to the module that created this wordlist. It will be used to release the wordlist when it is destroyed.
string $name Name of this wordlist.
string $file Path to the file where this wordlist is stored.
Definition at line 111 of file Wordlist.php.
References Erebot\Module\Wordlists\Wordlist\$file, Erebot\Module\Wordlists\Wordlist\$module, Erebot\Module\Wordlists\Wordlist\$name, and Erebot\Module\Wordlists\Wordlist\parseFile().
Erebot\Module\Wordlists\Wordlist::__destruct ()
Destroy the list, releasing any resource it may have used.
Definition at line 125 of file Wordlist.php.
Member Function Documentation
Erebot\Module\Wordlists\Wordlist::count ()
Returns the number of words in the list.
Return values
int Number of words in the list.
Definition at line 238 of file Wordlist.php.
Erebot\Module\Wordlists\Wordlist::findWord ($word)
Look for a word in the list.
Parameters
string $word The word to look for.
Return values
mixed If the given word was found, it is returned as it appears in the list (this may include case or accentuation variations). Otherwise, null is returned.
Definition at line 258 of file Wordlist.php.
Referenced by Erebot\Module\Wordlists\Wordlist\offsetExists().
Erebot\Module\Wordlists\Wordlist::free ()
Releases the current wordlist.
Definition at line 215 of file Wordlist.php.
Erebot\Module\Wordlists\Wordlist::getCollator ()
Returns the Collator object associated with this list.
Return values
Collator Collator for this list.
Definition at line 227 of file Wordlist.php.
References Erebot\Module\Wordlists\Wordlist\$collator.
Erebot\Module\Wordlists\Wordlist::getMetadata ($type)
Returns metadata associated with the list.
Parameters
string $type Type of metadata to return. See the constants named METADATA_* from this class for valid types.
Return values
mixed The requested metadata. This is a string for types that accept a single value (or null if the list does not provide any value) or an array for multi-valued types (an empty array may be returned in case the list does not provide any value).
Exceptions
Erebot::InvalidValueException The given metadata type is invalid.
Definition at line 342 of file Wordlist.php.
References Erebot\Module\Wordlists\Wordlist\$file, and Erebot\Module\Wordlists\Wordlist\$name.
Erebot\Module\Wordlists\Wordlist::offsetExists ($word)
Tests whether the given word exists in the list.
Parameters
string $word Some word whose existence will be tested.
Return values
bool true if the given word is present in this list, false otherwise.
See Also
Erebot::Module::Wordlists::Wordlist::findWord()
Definition at line 290 of file Wordlist.php.
References Erebot\Module\Wordlists\Wordlist\findWord().
Erebot\Module\Wordlists\Wordlist::offsetGet ($offset)
Returns the word at the given offset.
Parameters
int $offset Offset of the word to retrieve.
Return values
string The word at the given $offset.
Exceptions
Erebot::InvalidValueException The given offset is not an integer.
Definition at line 308 of file Wordlist.php.
Erebot\Module\Wordlists\Wordlist::parseFile ($file) protected
Parse the content of a SQLite file representing a list of words.
Parameters
string $file The full path to the SQLite file containing the list of words to use.
Exceptions
Erebot::InvalidValueException The locale indicated in the file was invalid.
Definition at line 145 of file Wordlist.php.
References Erebot\Module\Wordlists\Wordlist\$file, and Erebot\Module\Wordlists\Wordlist\$metadata.
Referenced by Erebot\Module\Wordlists\Wordlist\__construct().
Member Data Documentation
Erebot\Module\Wordlists\Wordlist::$metadata protected
Initial value:
= array(
        'version'       => null,
        'description'   => null,
        'author'        => array(),
        'locale'        => null,
        'license'       => null,
        'url'           => null,
        'keyword'       => array(),
    )
Metadata associated with this list.
Definition at line 63 of file Wordlist.php.
Referenced by Erebot\Module\Wordlists\Wordlist\parseFile().
The documentation for this class was generated from the following file:
src/Wordlists/Wordlist.php