Module_Math: Erebot\Module\Math\Parser Class Reference
Erebot\Module\Math\Parser Class Reference
Public Member Functions
__destruct ()
doParse ($yymajor, $yytokenvalue)
getResult ()
tokenName ($tokenType)
yy_accept ()
yy_find_reduce_action ($stateno, $iLookAhead)
yy_find_shift_action ($iLookAhead)
yy_get_expected_tokens ($token)
yy_is_expected_token ($token)
yy_parse_failed ()
yy_pop_parser_stack ()
yy_r0 ()
yy_r1 ()
yy_r2 ()
yy_r3 ()
yy_r4 ()
yy_r5 ()
yy_r6 ()
yy_r7 ()
yy_r8 ()
yy_r9 ()
yy_reduce ($yyruleno)
yy_shift ($yyNewState, $yyMajor, $yypMinor)
yy_syntax_error ($yymajor, $TOKEN)
Static Public Member Functions
static PrintTrace ()
static Trace ($TraceFILE, $zTracePrompt)
static yy_destructor ($yymajor, $yypminor)
Public Attributes
$yyerrcnt
$yyidx = -1
$yystack = array()
const TK_NUMBER = 9
const TK_OP_ADD = 1
const TK_OP_DIV = 4
const TK_OP_MOD = 5
const TK_OP_MUL = 3
const TK_OP_POW = 6
const TK_OP_SUB = 2
const TK_PAR_CLOSE = 8
const TK_PAR_OPEN = 7
const YY_ACCEPT_ACTION = 34
const YY_ERROR_ACTION = 33
const YY_NO_ACTION = 35
const YY_REDUCE_MAX = 7
const YY_REDUCE_USE_DFLT = -7
const YY_SHIFT_MAX = 16
const YY_SHIFT_USE_DFLT = -2
const YY_SZ_ACTTAB = 34
const YYERRORSYMBOL = 10
const YYERRSYMDT = 'yy0'
const YYFALLBACK = 0
const YYNOCODE = 14
const YYNRULE = 11
const YYNSTATE = 22
const YYSTACKDEPTH = 100
Static Public Attributes
static $yy_action
static $yy_default
static $yy_lookahead
static $yy_reduce_ofst
static $yy_shift_ofst
static $yyExpectedTokens
static $yyFallback
static $yyReduceMap
static $yyRuleInfo
static $yyRuleName
static $yyTokenName
static $yyTraceFILE
static $yyTracePrompt
Private Attributes
$_retvalue
$formulaResult = NULL
Detailed Description
Definition at line 105 of file Parser.php.
Constructor & Destructor Documentation
Erebot\Module\Math\Parser::__destruct ()
Deallocate and destroy a parser. Destructors are all called for all stack elements before shutting the parser down.
Definition at line 437 of file Parser.php.
References Erebot\Module\Math\Parser\yy_pop_parser_stack().
Member Function Documentation
Erebot\Module\Math\Parser::doParse ($yymajor, $yytokenvalue)
The main parser program.
The first argument is the major token number. The second is the token value string as scanned from the input.
Parameters
int $yymajor the token number
mixed $yytokenvalue the token value
mixed ... any extra arguments that should be passed to handlers
Returns
void
Definition at line 966 of file Parser.php.
References Erebot\Module\Math\Parser\yy_accept(), Erebot\Module\Math\Parser\yy_destructor(), Erebot\Module\Math\Parser\yy_find_shift_action(), Erebot\Module\Math\Parser\yy_is_expected_token(), Erebot\Module\Math\Parser\yy_parse_failed(), Erebot\Module\Math\Parser\yy_pop_parser_stack(), Erebot\Module\Math\Parser\yy_reduce(), Erebot\Module\Math\Parser\yy_shift(), and Erebot\Module\Math\Parser\yy_syntax_error().
static Erebot\Module\Math\Parser::PrintTrace () static
Output debug information to output (php://output stream)
Definition at line 307 of file Parser.php.
Erebot\Module\Math\Parser::tokenName ($tokenType)
This function returns the symbolic name associated with a token value.
Parameters
int
Returns
string
Definition at line 371 of file Parser.php.
static Erebot\Module\Math\Parser::Trace ($TraceFILE, $zTracePrompt) static
Turn parser tracing on by giving a stream to which to write the trace and a prompt to preface each trace message. Tracing is turned off by making either argument NULL
Inputs:
A stream resource to which trace output should be written. If NULL, then tracing is turned off.
A prefix string written at the beginning of every line of trace output. If NULL, then tracing is turned off.
Outputs:
None.
Parameters
resource
string
Definition at line 293 of file Parser.php.
Erebot\Module\Math\Parser::yy_accept ()
The following is executed when the parser accepts
parse_accept code is inserted here
Definition at line 942 of file Parser.php.
References Erebot\Module\Math\Parser\yy_pop_parser_stack().
Referenced by Erebot\Module\Math\Parser\doParse(), and Erebot\Module\Math\Parser\yy_reduce().
static Erebot\Module\Math\Parser::yy_destructor ($yymajor, $yypminor) static
The following function deletes the value associated with a symbol. The symbol can be either a terminal or nonterminal.
Parameters
int the symbol code
mixed the symbol's value
Definition at line 389 of file Parser.php.
Referenced by Erebot\Module\Math\Parser\doParse().
Erebot\Module\Math\Parser::yy_find_reduce_action ($stateno, $iLookAhead)
Find the appropriate action for a parser given the non-terminal look-ahead token $iLookAhead.
If the look-ahead token is self::YYNOCODE, then check to see if the action is independent of the look-ahead. If it is, return the action, otherwise return self::YY_NO_ACTION.
Parameters
int Current state number
int The look-ahead token
Definition at line 652 of file Parser.php.
Referenced by Erebot\Module\Math\Parser\yy_get_expected_tokens(), Erebot\Module\Math\Parser\yy_is_expected_token(), and Erebot\Module\Math\Parser\yy_reduce().
Erebot\Module\Math\Parser::yy_find_shift_action ($iLookAhead)
Find the appropriate action for a parser given the terminal look-ahead token iLookAhead.
If the look-ahead token is YYNOCODE, then check to see if the action is independent of the look-ahead. If it is, return the action, otherwise return YY_NO_ACTION.
Parameters
int The look-ahead token
Definition at line 608 of file Parser.php.
Referenced by Erebot\Module\Math\Parser\doParse(), Erebot\Module\Math\Parser\yy_get_expected_tokens(), and Erebot\Module\Math\Parser\yy_is_expected_token().
Erebot\Module\Math\Parser::yy_get_expected_tokens ($token)
Based on the current state and parser stack, get a list of all possible lookahead tokens
Parameters
int
Returns
array
Definition at line 453 of file Parser.php.
References Erebot\Module\Math\Parser\yy_find_reduce_action(), and Erebot\Module\Math\Parser\yy_find_shift_action().
Erebot\Module\Math\Parser::yy_is_expected_token ($token)
Based on the parser state and current parser stack, determine whether the lookahead token is possible.
The parser will convert the token value to an error token if not. This catches some unusual edge cases where the parser would fail.
Parameters
int
Returns
bool
Definition at line 528 of file Parser.php.
References Erebot\Module\Math\Parser\yy_find_reduce_action(), and Erebot\Module\Math\Parser\yy_find_shift_action().
Referenced by Erebot\Module\Math\Parser\doParse().
Erebot\Module\Math\Parser::yy_parse_failed ()
The following code executes when the parse fails
Code from parse_fail is inserted here
Definition at line 912 of file Parser.php.
References Erebot\Module\Math\Parser\yy_pop_parser_stack().
Referenced by Erebot\Module\Math\Parser\doParse().
Erebot\Module\Math\Parser::yy_pop_parser_stack ()
Pop the parser's stack once.
If there is a destructor routine associated with the token which is popped from the stack, then call it.
Return the major token number for the symbol popped.
Parameters
ParseyyParser
Returns
int
Definition at line 416 of file Parser.php.
Referenced by Erebot\Module\Math\Parser\__destruct(), Erebot\Module\Math\Parser\doParse(), Erebot\Module\Math\Parser\yy_accept(), Erebot\Module\Math\Parser\yy_parse_failed(), and Erebot\Module\Math\Parser\yy_shift().
Erebot\Module\Math\Parser::yy_reduce ($yyruleno)
Perform a reduce action and the shift that must immediately follow the reduce.
For a rule such as:
A ::= B blah C. { dosomething(); }
This function will first call the action, if any, ("dosomething();" in our example), and then it will pop three states from the stack, one for each entry on the right-hand side of the expression (B, blah, and C in our example rule), and then push the result of the action back on to the stack with the resulting state reduced to (as described in the .out file)
Parameters
int Number of the rule by which to reduce
Definition at line 857 of file Parser.php.
References Erebot\Module\Math\Parser\$_retvalue, Erebot\Module\Math\Parser\yy_accept(), Erebot\Module\Math\Parser\yy_find_reduce_action(), and Erebot\Module\Math\Parser\yy_shift().
Referenced by Erebot\Module\Math\Parser\doParse().
Erebot\Module\Math\Parser::yy_shift ($yyNewState, $yyMajor, $yypMinor)
Perform a shift action.
Parameters
int The new state to shift in
int The major token to shift in
mixed the minor token to shift in
Definition at line 681 of file Parser.php.
References Erebot\Module\Math\Parser\yy_pop_parser_stack().
Referenced by Erebot\Module\Math\Parser\doParse(), and Erebot\Module\Math\Parser\yy_reduce().
Erebot\Module\Math\Parser::yy_syntax_error ($yymajor, $TOKEN)
The following code executes when a syntax error first occurs.
syntax_error code is inserted here
Parameters
int The major type of the error token
mixed The minor type of the error token
Definition at line 931 of file Parser.php.
Referenced by Erebot\Module\Math\Parser\doParse().
Member Data Documentation
Erebot\Module\Math\Parser::$_retvalue private
placeholder for the left hand side in a reduce operation.
For a parser with a rule like this:
rule(A) ::= B. { A = 1; }
The parser will translate to something like:
function yy_r0(){$this->_retvalue = 1;}
Definition at line 837 of file Parser.php.
Referenced by Erebot\Module\Math\Parser\yy_reduce().
Erebot\Module\Math\Parser::$yy_action static
Initial value:
= array(
      6,    1,    3,    4,    5,    2,   10,   17,    2,    6,
      1,    3,    4,    5,    2,   12,   13,   34,    9,   21,
     19,    7,   26,   18,   20,    3,    4,    5,    2,   11,
     15,   14,   16,    8,
    )
Definition at line 188 of file Parser.php.
Erebot\Module\Math\Parser::$yy_default static
Initial value:
= array(
     33,   33,   33,   33,   33,   33,   33,   33,   33,   22,
     25,   24,   33,   33,   27,   28,   26,   23,   32,   31,
     29,   30,
)
Definition at line 235 of file Parser.php.
Erebot\Module\Math\Parser::$yy_lookahead static
Initial value:
= array(
      1,    2,    3,    4,    5,    6,   12,    8,    6,    1,
      2,    3,    4,    5,    6,    1,    2,   11,   12,    9,
      9,    7,   13,    9,   12,    3,    4,    5,    6,   12,
     12,   12,   12,   12,
)
Definition at line 194 of file Parser.php.
Erebot\Module\Math\Parser::$yy_reduce_ofst static
Initial value:
= array(
      6,   -6,   12,   20,   19,   18,   17,   21,
)
Definition at line 208 of file Parser.php.
Erebot\Module\Math\Parser::$yy_shift_ofst static
Initial value:
= array(
     14,   14,   14,   14,   14,   14,   14,   14,   -1,    8,
     22,   22,   10,   11,    2,    2,    2,
)
Definition at line 202 of file Parser.php.
Erebot\Module\Math\Parser::$yyExpectedTokens static
Initial value:
= array(
         array(1, 2, 7, 9, ),
         array(1, 2, 7, 9, ),
         array(1, 2, 7, 9, ),
         array(1, 2, 7, 9, ),
         array(1, 2, 7, 9, ),
         array(1, 2, 7, 9, ),
         array(1, 2, 7, 9, ),
         array(1, 2, 7, 9, ),
         array(1, 2, 3, 4, 5, 6, 8, ),
         array(1, 2, 3, 4, 5, 6, ),
         array(3, 4, 5, 6, ),
         array(3, 4, 5, 6, ),
         array(9, ),
         array(9, ),
         array(6, ),
         array(6, ),
         array(6, ),
         array(),
         array(),
         array(),
         array(),
         array(),
)
Definition at line 211 of file Parser.php.
Erebot\Module\Math\Parser::$yyFallback static
Initial value:
= array(
    )
The next table maps tokens into fallback tokens. If a construct like the following:
 %fallback ID X Y Z.
appears in the grammer, then ID becomes a fallback token for X, Y, and Z. Whenever one of the tokens X, Y, or Z is input to the parser but it does not parse, the type of the token is changed to ID and the parse is retried before an error is thrown.
Definition at line 272 of file Parser.php.
Erebot\Module\Math\Parser::$yyReduceMap static
Initial value:
= array(
        0 => 0,
        1 => 1,
        2 => 2,
        3 => 3,
        4 => 4,
        5 => 5,
        6 => 6,
        7 => 7,
        8 => 8,
        10 => 8,
        9 => 9,
    )
The following table contains a mapping of reduce action to method name that handles the reduction.
If a rule is not set, it has no handler.
Definition at line 746 of file Parser.php.
Erebot\Module\Math\Parser::$yyRuleInfo static
Initial value:
= array(
  array( 'lhs' => 11, 'rhs' => 1 ),
  array( 'lhs' => 12, 'rhs' => 3 ),
  array( 'lhs' => 12, 'rhs' => 3 ),
  array( 'lhs' => 12, 'rhs' => 3 ),
  array( 'lhs' => 12, 'rhs' => 3 ),
  array( 'lhs' => 12, 'rhs' => 3 ),
  array( 'lhs' => 12, 'rhs' => 3 ),
  array( 'lhs' => 12, 'rhs' => 3 ),
  array( 'lhs' => 12, 'rhs' => 2 ),
  array( 'lhs' => 12, 'rhs' => 2 ),
  array( 'lhs' => 12, 'rhs' => 1 ),
    )
The following table contains information about every rule that is used during the reduce.
array(
 array(
  int $lhs;         Symbol on the left-hand side of the rule
  int $nrhs;     Number of right-hand side symbols in the rule
 ),...
);
Definition at line 726 of file Parser.php.
Erebot\Module\Math\Parser::$yyRuleName static
Initial value:
= array(
  "formula ::= exprPar",
  "exprPar ::= PAR_OPEN exprPar PAR_CLOSE",
  "exprPar ::= exprPar OP_ADD exprPar",
  "exprPar ::= exprPar OP_SUB exprPar",
  "exprPar ::= exprPar OP_MUL exprPar",
  "exprPar ::= exprPar OP_DIV exprPar",
  "exprPar ::= exprPar OP_MOD exprPar",
  "exprPar ::= exprPar OP_POW exprPar",
  "exprPar ::= OP_ADD NUMBER",
  "exprPar ::= OP_SUB NUMBER",
  "exprPar ::= NUMBER",
    )
Definition at line 351 of file Parser.php.
Erebot\Module\Math\Parser::$yyTokenName static
Initial value:
= array(
  '$',             'OP_ADD',        'OP_SUB',        'OP_MUL',
  'OP_DIV',        'OP_MOD',        'OP_POW',        'PAR_OPEN',
  'PAR_CLOSE',     'NUMBER',        'error',         'formula',
  'exprPar',
    )
Definition at line 340 of file Parser.php.
The documentation for this class was generated from the following file:
src/Math/Parser.php