Module_IrcTracker: Erebot_Module_IrcTracker Class Reference
Erebot_Module_IrcTracker Class Reference
A module that keeps track of users which are on the same IRC channels as the bot.
Public Member Functions
_reload ($flags)
byChannelModes ($chan, $modes, $negate=FALSE)
getCommonChans ($nick)
getHelp (Erebot_Interface_Event_Base_TextMessage $event, Erebot_Interface_TextWrapper $words)
getInfo ($token, $info, $args=array())
handleCapabilities (Erebot_Interface_EventHandler $handler, Erebot_Event_ServerCapabilities $event)
handleChanModeAddition (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_ChanModeGiven $event)
handleChanModeRemoval (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_ChanModeTaken $event)
handleJoin (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Join $event)
handleLeaving (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_Generic $event)
handleNames (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
handleNick (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Nick $event)
handleNotification (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_Source $event)
handleWho (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
IAL ($mask, $chan=NULL)
isOn ($chan, $nick=NULL)
removeUser (Erebot_Interface_Timer $timer, $nick)
startTracking ($nick, $cls= 'Erebot_Module_IrcTracker_Token')
userPrivileges ($chan, $nick)
Static Public Member Functions
static extractNick ($source)
Public Attributes
const INFO_HOST = 'Host'
Return the current hostname for some user.
const INFO_IDENT = 'Ident'
Return the current identity (in the IRC sense) for some user.
const INFO_ISON = 'IsOn'
Return whether the given user is currently connected or not.
const INFO_MASK = 'Mask'
Return the current IRC mask for some user.
const INFO_NICK = 'Nick'
Return the current nickname for some user.
Protected Member Functions
_removeUser ($nick)
_unload ()
_updateUser ($nick, $ident, $host)
Protected Attributes
$_chans
Maps channels to a list of tokens for users present in that channel.
$_hasUHNAMES
Whether the IRC server supports the UHNAMES extension or not.
$_ial
Internal Address List, à la mIRC.
$_nicks
Maps tokens to normalized nicknames.
$_sequence
Sequence number, incremented by 1 after each new token generation.
Detailed Description
A module that keeps track of users which are on the same IRC channels as the bot.
Definition at line 24 of file IrcTracker.php.
Member Function Documentation
Erebot_Module_IrcTracker::_reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot_Module_Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 72 of file IrcTracker.php.
Erebot_Module_IrcTracker::_removeUser ($nick) protected
Removes some user from the IAL.
Parameters
string $nick Nickname of the user that is to be removed from the IAL.
Definition at line 299 of file IrcTracker.php.
References getCommonChans().
Referenced by handleLeaving(), handleNick(), handleNotification(), and removeUser().
Erebot_Module_IrcTracker::_unload () protected
Frees the resources associated with this module.
Definition at line 172 of file IrcTracker.php.
Erebot_Module_IrcTracker::_updateUser ($nick, $ident, $host) protected
Updates the IAL with new information on some user.
Parameters
string $nick Some user's nickname whose IAL entry will be updated.
string $ident Some user's identity, in the IRC sense of the term.
string $host Some user's hostname.
Definition at line 249 of file IrcTracker.php.
Referenced by handleJoin(), handleNames(), handleNotification(), and handleWho().
Erebot_Module_IrcTracker::byChannelModes ($chan, $modes, $negate = FALSE)
Returns a list with the nicknames of all users that (do not) have some specific modes on them on some IRC channel.
Parameters
string $chan The IRC channel we're interested in.
array $modes Only return those users that have these statuses on the given IRC channel.
bool $negate Negate the search, ie. only return those users that DO NOT have the given statuses on the given IRC channel.
Return values
list Nicknames of all users matching the given criteria.
Exceptions
Erebot_NotFoundException The bot is not present on the given IRC channel and so the search cannot succeed.
Definition at line 994 of file IrcTracker.php.
static Erebot_Module_IrcTracker::extractNick ($source) static
Given some user's full IRC identity (nick!ident@host), this methods extracts and returns that user's nickname.
Parameters
string $source Some user's full IRC identity (as "nick!ident\@host").
Return values
string The nickname of the user represented by that identity.
Note
This method will still work as expected if given only a nickname to work with. Therefore, it is safe to call this method with the result of a previous invocation. Thus, the following snippet: Erebot_Module_IrcTracker::extractNick(Erebot_Module_IrcTracker::extractNick('foo!bar@baz')); will return "foo" as expected.
Definition at line 229 of file IrcTracker.php.
Erebot_Module_IrcTracker::getCommonChans ($nick)
Returns a list of IRC channels the bot and some other user have in common.
Parameters
string $nick Nickname of the user for which we want to know what channels (s)he shares with the bot.
Return values
list A list with the names of all IRC channels that user and the bot have in common.
Exceptions
Erebot_NotFoundException The given nickname does not match any known user.
Definition at line 857 of file IrcTracker.php.
Referenced by _removeUser(), and handleLeaving().
Erebot_Module_IrcTracker::getHelp (Erebot_Interface_Event_Base_TextMessage $event, Erebot_Interface_TextWrapper $words)
Definition at line 181 of file IrcTracker.php.
Erebot_Module_IrcTracker::getInfo ($token, $info, $args = array())
Returns information about some user given a token associated with that user.
Parameters
opaque $token Token associated with the user.
opaque $info The type of information we're interested in. This is one of the INFO_* constants provided by this class.
array $args (optional) Additional arguments for the query. Defaults to an empty array. At present time, this argument is only useful when you pass one of Erebot_Module_IrcTracker::INFO_HOST or Erebot_Module_IrcTracker::INFO_MASK as the value for $info. In this case, you may pass an array containing a boolean ($canonical) indicating the type of hostname canonicalization to apply. See also Erebot_Interface_Identity::getHost() for more information on the $canonical parameter.
Return values
mixed Requested information about that user. This may be NULL if the requested information has not been obtained yet.
Exceptions
Erebot_InvalidValueException The value for $info is invalid.
Erebot_NotFoundException The given $token does not match any known user.
Warning
This method is not meant to be called directly. Instead, you should call the equivalent methods (getNick(), getHost(), etc.) from the token returned by Erebot_Module_IrcTracker::startTracking().
Definition at line 760 of file IrcTracker.php.
Erebot_Module_IrcTracker::handleCapabilities (Erebot_Interface_EventHandler $handler, Erebot_Event_ServerCapabilities $event)
Handles server capabilities.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Event_ServerCapabilities $event An event referencing a module that can determine the IRC server's capabilities, such as Erebot_Module_ServerCapabilities.
(PHPMD.UnusedFormalParameter)
Definition at line 467 of file IrcTracker.php.
Erebot_Module_IrcTracker::handleChanModeAddition (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_ChanModeGiven $event)
Handles someone receiving a new status on an IRC channel, for example, when someone is OPped.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Base_ChanModeGiven $event Event indicating someone's status changed on an IRC channel the bot is currently on, giving that person new privileges.
(PHPMD.UnusedFormalParameter)
Definition at line 618 of file IrcTracker.php.
Erebot_Module_IrcTracker::handleChanModeRemoval (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_ChanModeTaken $event)
Handles someone losing his status on an IRC channel, for example, when someone is DEOPped.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Base_ChanModeTaken $event Event indicating someone's status changed on an IRC channel the bot is currently on, removing privileges from that person.
(PHPMD.UnusedFormalParameter)
Definition at line 649 of file IrcTracker.php.
Erebot_Module_IrcTracker::handleJoin (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Join $event)
Handles some user joining an IRC channel the bot is currently on.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Join $event Event indicating that some user joined a channel the bot is on.
(PHPMD.UnusedFormalParameter)
Definition at line 585 of file IrcTracker.php.
References _updateUser().
Erebot_Module_IrcTracker::handleLeaving (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_Generic $event)
Handles some user leaving an IRC channel. This may result from either a QUIT or KICK command.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Base_Generic $event An event indicating that some user is leaving an IRC channel the bot is on.
(PHPMD.UnusedFormalParameter)
Definition at line 408 of file IrcTracker.php.
References _removeUser(), and getCommonChans().
Erebot_Module_IrcTracker::handleNames (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
Handles a list with the nicknames of all users in a given IRC channel.
Parameters
Erebot_Interface_NumericHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Numeric $numeric A numeric event with the nicknames of users in an IRC channel the bot just joined. This is the same type of numeric event as when the NAMES command is issued.
(PHPMD.UnusedFormalParameter)
Definition at line 496 of file IrcTracker.php.
References _updateUser().
Erebot_Module_IrcTracker::handleNick (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Nick $event)
Handles a nick change.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Nick $event Nick change event.
(PHPMD.UnusedFormalParameter)
Definition at line 375 of file IrcTracker.php.
References _removeUser().
Erebot_Module_IrcTracker::handleNotification (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Base_Source $event)
Handles a notification about some user (dis)connecting from/to the IRC network.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Base_Source $event Notification.
(PHPMD.UnusedFormalParameter)
Definition at line 345 of file IrcTracker.php.
References _removeUser(), and _updateUser().
Erebot_Module_IrcTracker::handleWho (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
Handles information about some user.
Parameters
Erebot_Interface_NumericHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Numeric $numeric Numeric event containing some user's nickname, IRC identity and hostname.
(PHPMD.UnusedFormalParameter)
Definition at line 563 of file IrcTracker.php.
References _updateUser().
Erebot_Module_IrcTracker::IAL ($mask, $chan = NULL)
Returns a list with the masks of all users that match a given (wildcard) mask and are on the given IRC channel.
Parameters
string $mask A wildcard match to use to filter out users (eg. "*!*@*.fr" to find all users connected using a french ISP).
mixed $chan (optional) Only search for users that have joined this IRC channel (given by its name, as a string). May also be set to NULL to search for all users known to the bot, no matter what channels they are currently on. Defaults to NULL.
Return values
list A list with the masks of all users matching the given criteria.
Exceptions
Erebot_NotFoundException The given channel name does not match the name of any channel the bot is on.
Definition at line 901 of file IrcTracker.php.
Erebot_Module_IrcTracker::isOn ($chan, $nick = NULL)
Indicates whether some user is present on a given IRC channel.
Parameters
string $chan IRC channel that user must be on.
mixed $nick (optional) Either some user's nickname (a string) or NULL. Defaults to NULL. When this parameter is NULL, this method tests whether the bot is on the given IRC channel or not.
Return values
bool TRUE is the given user is on that IRC channel, FALSE otherwise.
Definition at line 828 of file IrcTracker.php.
Erebot_Module_IrcTracker::removeUser (Erebot_Interface_Timer $timer, $nick)
Removes some user from the IAL when the timer associated with their disconnection times out.
Parameters
Erebot_Interface_Timer $timer Timer associated with the user's disconnection.
string $nick Nickname of the user to remove from the IAL.
(PHPMD.UnusedFormalParameter)
Definition at line 328 of file IrcTracker.php.
References _removeUser().
Erebot_Module_IrcTracker::startTracking ($nick, $cls = 'Erebot_Module_IrcTracker_Token')
Returns a tracking token for some user.
Parameters
string $nick The nickname of some user we want to start tracking.
string $cls (optional) Class to use to create the token. Defaults to Erebot_Module_IrcTracker_Token.
Return values
mixed A token that can later be used to return information on that user (such as his/her nickname, IRC identity, hostname and whether that person is still online or not).
Exceptions
Erebot_NotFoundException There is currently no user connected on an IRC channel the bot is on matching the given nickname.
Definition at line 692 of file IrcTracker.php.
Erebot_Module_IrcTracker::userPrivileges ($chan, $nick)
Returns channel status associated with the given user.
Parameters
string $chan The IRC channel we're interested in.
string $nick Nickname of the user whose status on the given channel we're interested in.
Return values
list A list with the status/privileges for that user on the given channel. Each status is given by the letter for the channel mode that refers to it (eg. "o" for "operator status").
Exceptions
Erebot_NotFoundException The given channel or nickname is not not known to the bot.
Definition at line 962 of file IrcTracker.php.
The documentation for this class was generated from the following file:
src/Erebot/Module/IrcTracker.php