Module_WebGetter: Erebot\Module\WebGetter Class Reference
Erebot\Module\WebGetter Class Reference
A module that fetches content off an internet website.
Public Member Functions
getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event,\Erebot\Interfaces\TextWrapper $words)
handleRequest (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\TextMessage $event)
reload ($flags)
Protected Member Functions
getParams ($index, $params, $context)
getPostData ($index, $params, $context)
prepareContext ($botFmt, $text)
processResponse (\Requests_Response $response, $encoding, $index, $params, &$context)
Static Protected Member Functions
static injectContext ($msg, $args)
Protected Attributes
$indexes
Maps triggers to their index in the configuration.
Detailed Description
A module that fetches content off an internet website.
This module can be configured to respond to certain commands by fetching content from an internet website, grabbing some pieces of information using XPath expressions and then outputting those information to an IRC channel using a pre-configured format.
Definition at line 32 of file WebGetter.php.
Member Function Documentation
Erebot\Module\WebGetter::getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event, \Erebot\Interfaces\TextWrapper $words)
Provides help about this module.
Parameters
Erebot::Interfaces::Event::Base::TextMessage $event Some help request.
Erebot::Interfaces::TextWrapper $words Parameters passed with the request. This is the same as this module's name when help is requested on the module itself (in opposition with help on a specific command provided by the module).
Definition at line 120 of file WebGetter.php.
Erebot\Module\WebGetter::getParams ($index, $params, $context) protected
Returns the GET parameters for the request.
Parameters
int $index Index of the trigger.
array $params A list with the names of the parameters associated with this module.
array $context Context for this HTTP request.
Return values
string The request's parameters, in query string format.
Definition at line 284 of file WebGetter.php.
Referenced by Erebot\Module\WebGetter\handleRequest().
Erebot\Module\WebGetter::getPostData ($index, $params, $context) protected
Returns POST data for the HTTP request.
Parameters
int $index Index of the trigger.
array $params A list with the names of the parameters associated with this module.
array $context Context for this HTTP request.
Return values
string POST data.
Definition at line 315 of file WebGetter.php.
Referenced by Erebot\Module\WebGetter\handleRequest().
Erebot\Module\WebGetter::handleRequest (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\TextMessage $event)
Handles a request to fetch some content off an internet website.
Parameters
Erebot::Interfaces::EventHandler $handler Handler responsible for triggering this method.
Erebot::Interfaces::Event::Base::TextMessage $event Actual request to fetch some content.
Return values
null This method does not return any value.
(PHPMD.UnusedFormalParameter)
Definition at line 469 of file WebGetter.php.
References Erebot\Module\WebGetter\getParams(), Erebot\Module\WebGetter\getPostData(), Erebot\Module\WebGetter\prepareContext(), and Erebot\Module\WebGetter\processResponse().
static Erebot\Module\WebGetter::injectContext ($msg, $args) static protected
Python-like formatting, compatible with dictionary-based formats (%(foo)s).
Parameters
string $msg
mixed $args Either null or a scalar type or an array, possibly containing the values that will make up the substitutions in $msg.
Return values
string Resulting string after all substitutions have been performed.
Note
If $args is null, $msg is returned untouched. If a scalar was passed, this method basically returns the same thing as sprintf($msg, $args). In an array was used, this does a job similar to Python's "%(foo)s %(bar)d %(baz)f" % dictionary, except that only the "s", "d" & "f" formats are supported and extra specifiers (eg. width specification for float formats) are not supported.
Copy/pasted from Plop :)
Definition at line 205 of file WebGetter.php.
Erebot\Module\WebGetter::prepareContext ($botFmt, $text) protected
Returns the context for a new HTTP request.
Parameters
Erebot::IntlInterface $botFmt Main formatter used by the bot.
Erebot::Interfaces::TextWrapper $text The text from the IRC event.
Return values
array Array containing the new context.
Definition at line 246 of file WebGetter.php.
Referenced by Erebot\Module\WebGetter\handleRequest().
Erebot\Module\WebGetter::processResponse (\Requests_Response $response, $encoding, $index, $params, & $context) protected
Processes the response to an HTTP request.
Parameters
opaque $response Response to the HTTP request.
mixed $encoding Encoding for the response. Either null (do not change the encoding) or a string with the name of the encoding.
int $index Index of the trigger.
array $params A list with the names of the parameters associated with this module.
array $context Context for this HTTP request.
Returns
This method does not return anything.
Postcondition
The context is updated with the information extracted from the HTTP response.
Definition at line 358 of file WebGetter.php.
Referenced by Erebot\Module\WebGetter\handleRequest().
Erebot\Module\WebGetter::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 49 of file WebGetter.php.
The documentation for this class was generated from the following file:
src/WebGetter.php