Module_AZ: Erebot\Module\AZ\Game Class Reference
Erebot\Module\AZ\Game Class Reference
Actual A-Z game implementation.
Public Member Functions
__construct (\Erebot\Module\Wordlists $wordlists, $lists)
__destruct ()
Destructor.
getAttemptsCount ()
getElapsedTime ()
getInvalidWordsCount ()
getLoadedListsNames ()
getMaximum ()
getMinimum ()
getTarget ()
getWordsCount ()
proposeWord ($word)
Protected Member Functions
compareWords ($a, $b)
isValidWord ($word)
Protected Attributes
$attempts
Number of attempts made to find the correct word.
$collator
A collator, providing case-insensitive comparison.
$invalidWords
Number of invalid words that were proposed (that passed WORD_FILTER).
$lists
Lists of words used in this game.
$max
Higher part of the current range (null if undefined).
$min
Lower part of the current range (null if undefined).
$started
Timestamp for game start.
$target
The actual word that contestants must guess.
$wordsCount
Number of words in the currently loaded wordlists.
Detailed Description
Actual A-Z game implementation.
This class does all the heavy work.
Definition at line 27 of file Game.php.
Constructor & Destructor Documentation
Erebot\Module\AZ\Game::__construct (\Erebot\Module\Wordlists $wordlists, $lists)
Creates a new instance of the game.
Parameters
Erebot::Module::Wordlists::$wordlists An instance of Erebot::Module::Wordlists, the module responsible for providing access to wordlists.
array $lists A list with the name of the dictionaries from which the target word may be selected.
Exceptions
Erebot::Module::AZ::IncompatibleException The given wordlists are not compatible with each other (eg. they do not use the same locales).
Erebot::Module::AZ::NotEnoughWordsException There are not enough words in the selected lists.
Note
Invalid list names and lists whose content cannot be parsed are silently ignored.
Definition at line 80 of file Game.php.
References Erebot\Module\AZ\Game\$collator, Erebot\Module\AZ\Game\$lists, and Erebot\Module\AZ\Game\$target.
Member Function Documentation
Erebot\Module\AZ\Game::compareWords ($a, $b) protected
Compare two words in a case-insensitive fashion.
Parameters
mixed $a First word to use in the comparison. Can be null if unavailable.
mixed $b Second word to use in the comparison. Can be null if unavailable.
Return values
int Returns < 0 if $a is less than $b; > 0 if $a is greater than $b, and 0 if they are equal. The comparison is case-insentive.
Definition at line 334 of file Game.php.
Referenced by Erebot\Module\AZ\Game\isValidWord(), and Erebot\Module\AZ\Game\proposeWord().
Erebot\Module\AZ\Game::getAttemptsCount ()
Returns the number of attempts made to guess the target word.
Return values
int Number of attempts made to find the target word.
Definition at line 181 of file Game.php.
References Erebot\Module\AZ\Game\$attempts.
Erebot\Module\AZ\Game::getElapsedTime ()
Returns the game's duration in seconds.
Return values
int Elapsed time since the game was started.
Definition at line 350 of file Game.php.
References Erebot\Module\AZ\Game\$started.
Erebot\Module\AZ\Game::getInvalidWordsCount ()
Returns the number of invalid words that were proposed during this game.
Return values
int Number of invalid words proposed.
Definition at line 193 of file Game.php.
References Erebot\Module\AZ\Game\$invalidWords.
Erebot\Module\AZ\Game::getLoadedListsNames ()
Returns the names of all currently loaded wordlists.
Return values
array A list with the names of all currently loaded wordlists.
Definition at line 306 of file Game.php.
Erebot\Module\AZ\Game::getMaximum ()
Returns the last word in the currently active wordlists.
Return values
string Last word in currently active wordlists.
Definition at line 157 of file Game.php.
References Erebot\Module\AZ\Game\$max.
Erebot\Module\AZ\Game::getMinimum ()
Returns the first word in the currently active wordlists.
Return values
string First word in currently active wordlists.
Definition at line 145 of file Game.php.
References Erebot\Module\AZ\Game\$min.
Erebot\Module\AZ\Game::getTarget ()
Returns the target word for this game.
Return values
string Target word for this round.
Definition at line 168 of file Game.php.
References Erebot\Module\AZ\Game\$target.
Erebot\Module\AZ\Game::getWordsCount ()
Returns the number of words contained in the currently loaded wordlists.
Return values
int Number of words in the current lists.
Definition at line 205 of file Game.php.
References Erebot\Module\AZ\Game\$wordsCount.
Erebot\Module\AZ\Game::isValidWord ($word) protected
Checks whether some text is a valid word for the current game.
This method checks whether the given text contains something that is recognized as a word in the current range, and part of the currently active wordlists.
Parameters
string $word Some "word" to test.
Return values
mixed null is returned when the given $word does not look like a word (eg. "#$!@") or is outside the game's current range. false is returned when this word is not part of a currently active wordlist. Otherwise, the word is returned the way it is written in the list (which may include case or accentuation variations).
Definition at line 232 of file Game.php.
References Erebot\Module\AZ\Game\compareWords().
Referenced by Erebot\Module\AZ\Game\proposeWord().
Erebot\Module\AZ\Game::proposeWord ($word)
Submit a proposition for this game.
Parameters
string $word The word to propose.
Return values
mixed null is returned when the given $word does not look like a word (eg. "#$!@") or is outside the game's current range. true is returned when the target word has been proposed (we have a winner!). Otherwise, false is returned.
Exceptions
Erebot::Module::AZ::InvalidWordException The given $word may have looked like a valid word at first, but really isn't. Such words increase the "invalid words" counter.
Definition at line 272 of file Game.php.
References Erebot\Module\AZ\Game\compareWords(), and Erebot\Module\AZ\Game\isValidWord().
The documentation for this class was generated from the following file:
src/AZ/Game.php