Module_Helper: Erebot\Module\Helper Class Reference
Erebot\Module\Helper Class Reference
A module that can be used by other modules to register a method to call whenever someone asks for help on them.
Public Member Functions
getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event,\Erebot\Interfaces\TextWrapper $words)
handleHelp (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\TextMessage $event)
realRegisterHelpMethod (\Erebot\Module\Base $module,\Erebot\CallableInterface $callback)
reload ($flags)
Static Public Member Functions
static normalizeModule ($moduleName)
Protected Member Functions
checkCallback (\Erebot\StylingInterface $fmt, $target, $chan, $moduleName)
getModules ($chan)
Static Protected Member Functions
static getModuleName (\Erebot\Interfaces\TextWrapper &$text)
Protected Attributes
$handler
Handler used by this module to detect help requests.
$helpCallbacks
Maps each module to the method that handles help requests for it.
$trigger
Token associated with this module's trigger.
Detailed Description
A module that can be used by other modules to register a method to call whenever someone asks for help on them.
Definition at line 27 of file Helper.php.
Member Function Documentation
Erebot\Module\Helper::checkCallback (\Erebot\StylingInterface $fmt, $target, $chan, $moduleName) protected
Checks whether the given module exists and whether an help callback has been registered for that module.
Parameters
Erebot::StylingInterface $fmt Formatter for messages produced by this method.
string $target Some user's nickname or IRC channel name messages emitted by this method will be sent to.
mixed $chan Either the name of an IRC channel or null. This is used to retrieve a list of all modules enabled for that channel.
string $moduleName Name of the module the help request is about.
Return values
bool true if the given module exists and some callback was registered to handle help requests for it, or false otherwise.
Definition at line 219 of file Helper.php.
Referenced by Erebot\Module\Helper\handleHelp().
Erebot\Module\Helper::getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event, \Erebot\Interfaces\TextWrapper $words)
Provides help about this module.
Parameters
Erebot::Interfaces::Event::Base::TextMessage $event Some help request.
Erebot::Interfaces::TextWrapper $words Parameters passed with the request. This is the same as this module's name when help is requested on the module itself (in opposition with help on a specific command provided by the module).
Definition at line 156 of file Helper.php.
References Erebot\Module\Helper\$trigger.
static Erebot\Module\Helper::getModuleName (\Erebot\Interfaces\TextWrapper & $text) static protected
Extracts the name of a module from some help request.
Parameters
Erebot::Interfaces::TextWrapper $text Text of the help request from which the module name will be extracted.
Return values
mixed Either the name of the module the help request relates to or null if the request is about a command.
Postcondition
If the request was related to a module, the module's name is removed from the request.
Definition at line 268 of file Helper.php.
Erebot\Module\Helper::handleHelp (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\TextMessage $event)
Handles a request for help on some module/command.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Contents of the help request (eg. name of a module or command).
(PHPMD.UnusedFormalParameter) (PHPMD.UnusedLocalVariable)
Definition at line 294 of file Helper.php.
References Erebot\Module\Helper\checkCallback().
Erebot\Module\Helper::realRegisterHelpMethod (\Erebot\Module\Base $module, \Erebot\CallableInterface $callback)
Registers a method to call back whenever someone requests help on a specific module.
Parameters
Erebot::Module::Base $module The module the method provides help for.
Erebot::CallableInterface $callback The method/function to call whenever someone asks for help on that particular module or a command provided by it.
Return values
bool true if the call succeeded, false otherwise.
Definition at line 114 of file Helper.php.
Referenced by Erebot\Module\Helper\reload().
Erebot\Module\Helper::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 51 of file Helper.php.
References Erebot\Module\Helper\$trigger, and Erebot\Module\Helper\realRegisterHelpMethod().
The documentation for this class was generated from the following file:
src/Helper.php