Module_AZ: Erebot\Module\AZ Class Reference
Erebot\Module\AZ Class Reference
A module that provides a game called "A-Z".
Public Member Functions
handleGame (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleRawText (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
reload ($flags)
Protected Member Functions
handleCreate (\Erebot\Interfaces\Event\ChanText $event)
handleExisting (\Erebot\Interfaces\Event\ChanText $event)
handleList (\Erebot\Interfaces\Event\ChanText $event)
handleStop (\Erebot\Interfaces\Event\ChanText $event)
Protected Attributes
$chans
Associative array mapping channels to games currently in progress.
$handlers
Handlers created by this module.
$triggers
Triggers registered by this module (as tokens).
Detailed Description
A module that provides a game called "A-Z".
In the "A-Z" game, the bot selects a word from a dictionary and contestants must guess that word. Each time a word is proposed, the range of possible words is reduced, until only one word remains.
Definition at line 30 of file AZ.php.
Member Function Documentation
Erebot\Module\AZ::handleCreate (\Erebot\Interfaces\Event\ChanText $event) protected
Handles a request to create a new game.
Parameters
Erebot::Interfaces::Event::Base::ChanText $event A message asking the bot to create a new game.
(PHPMD.UnusedLocalVariable)
Definition at line 217 of file AZ.php.
Referenced by Erebot\Module\AZ\handleGame().
Erebot\Module\AZ::handleExisting (\Erebot\Interfaces\Event\ChanText $event) protected
Handles a request to display information about a currently running game.
Parameters
Erebot::Interfaces::Event::Base::ChanText $event A message asking the bot to display information about a running game.
Definition at line 143 of file AZ.php.
Referenced by Erebot\Module\AZ\handleGame().
Erebot\Module\AZ::handleGame (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
This method can be used to create or stop a game, display information about a running game or to list available dictionaries.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::ChanText $event A message that asks the bot to create a new game, stop a running game, display information about a running game or list available dictionaries.
(PHPMD.UnusedFormalParameter)
Definition at line 290 of file AZ.php.
References Erebot\Module\AZ\handleCreate(), Erebot\Module\AZ\handleExisting(), Erebot\Module\AZ\handleList(), and Erebot\Module\AZ\handleStop().
Erebot\Module\AZ::handleList (\Erebot\Interfaces\Event\ChanText $event) protected
Handles a request to list available dictionaries.
Parameters
Erebot::Interfaces::Event::Base::ChanText $event A message asking the bot to list available dictionaries.
Definition at line 111 of file AZ.php.
Referenced by Erebot\Module\AZ\handleGame().
Erebot\Module\AZ::handleRawText (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles messages: words are interpreted as propositions for the game.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::ChanText $event A message with a proposition for the game.
(PHPMD.UnusedFormalParameter)
Definition at line 325 of file AZ.php.
Erebot\Module\AZ::handleStop (\Erebot\Interfaces\Event\ChanText $event) protected
Handles a request to stop the game.
Parameters
Erebot::Interfaces::Event::Base::ChanText $event A message asking the bot to stop the game.
Definition at line 185 of file AZ.php.
Referenced by Erebot\Module\AZ\handleGame().
Erebot\Module\AZ::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 53 of file AZ.php.
The documentation for this class was generated from the following file:
src/AZ.php