Module_IrcConnector: Erebot_Module_IrcConnector Class Reference
Erebot_Module_IrcConnector Class Reference
Public Member Functions
_reload ($flags)
getBotHostname ()
getBotIdentity ()
getBotNickname ()
getBotRealname ()
getHelp (Erebot_Interface_Event_Base_TextMessage $event, Erebot_Interface_TextWrapper $words)
getNetPassword ()
getURIFactory ()
handleExit (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Exit $event)
handleLogon (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Logon $event)
handleSTARTTLSFailure (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
handleSTARTTLSSuccess (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
setURIFactory ($cls)
Protected Member Functions
_unload ()
sendCredentials ()
Protected Attributes
$_hostname
Hostname the bot will pretend to be coming from (possibly a fake).
$_identity
Identity of the bot on IRC.
$_nickname
Nickname to use to connect to the IRC server.
$_password
Password of the IRC server.
$_realname
The bot's real name on IRC.
$_uriFactory = 'Erebot_URI'
Class used to parse Uniform Resource Identifiers.
Detailed Description
A module which can send the proper sequence of commands to an IRC server to proceed to the "registered" phase.
This module also supports security upgrades (upgrading from a plain-text connection to a TLS encrypted one) using the STARTTLS extension.
See Also
See http://wiki.inspircd.org/STARTTLS_Documentation for more information on the STARTTLS extension.
Definition at line 31 of file IrcConnector.php.
Member Function Documentation
Erebot_Module_IrcConnector::_reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot_Module_Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 65 of file IrcConnector.php.
Erebot_Module_IrcConnector::_unload () protected
Definition at line 87 of file IrcConnector.php.
Erebot_Module_IrcConnector::getBotHostname ()
Returns the bot's hostname.
Return values
string The bot's hostname.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current hostname if it was changed at a later time.
Most IRC servers ignore the hostname announced by clients and do a reverse DNS query on their IP address instead (this is a security measure). The value returned by this method will generally be different from the value used by the server.
Definition at line 393 of file IrcConnector.php.
References $_hostname.
Erebot_Module_IrcConnector::getBotIdentity ()
Returns the bot's identity.
Return values
string The bot's ident.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current identity if it was changed at a later time.
Definition at line 369 of file IrcConnector.php.
References $_identity.
Erebot_Module_IrcConnector::getBotNickname ()
Returns the bot's nickname.
Return values
string The bot's nickname.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current nickname if it was changed at a later time.
Definition at line 352 of file IrcConnector.php.
References $_nickname.
Erebot_Module_IrcConnector::getBotRealname ()
Returns the bot's real name (or GECOS information).
Return values
string The bot's real name.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current real name if it was changed at a later time.
Definition at line 410 of file IrcConnector.php.
References $_realname.
Erebot_Module_IrcConnector::getHelp (Erebot_Interface_Event_Base_TextMessage $event, Erebot_Interface_TextWrapper $words)
Definition at line 92 of file IrcConnector.php.
Erebot_Module_IrcConnector::getNetPassword ()
Returns the password used to connect to this IRC network.
Return values
string The password used to connect to this IRC network.
Note
This method will return an empty string if no password was used to contact this IRC network.
Definition at line 335 of file IrcConnector.php.
References $_password.
Erebot_Module_IrcConnector::getURIFactory ()
Handles a connection to an IRC server. This method is called during the logon phase, right after a TCP connection has been established but before the IRC server accepted us.
Return values
string Name of the class used to parse Uniform Resource Identifiers.
Definition at line 148 of file IrcConnector.php.
References $_uriFactory.
Erebot_Module_IrcConnector::handleExit (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Exit $event)
Handles an exit request (eg. when the bot receives the SIGTERM signal).
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Event_Exit $event Exit event.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter)
Definition at line 260 of file IrcConnector.php.
Erebot_Module_IrcConnector::handleLogon (Erebot_Interface_EventHandler $handler, Erebot_Interface_Event_Logon $event)
Handles a connection to an IRC server. This method is called during the logon phase, right after a TCP connection has been established but before the IRC server accepted us.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Event_Logon $event Logon event.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter)
Definition at line 211 of file IrcConnector.php.
References sendCredentials().
Erebot_Module_IrcConnector::handleSTARTTLSFailure (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
Handles a failed TLS session.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Event_Numeric $numeric Numeric event indicating that the TLS session could not be established.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter)
Definition at line 317 of file IrcConnector.php.
Erebot_Module_IrcConnector::handleSTARTTLSSuccess (Erebot_Interface_NumericHandler $handler, Erebot_Interface_Event_Numeric $numeric)
Handles a successful TLS session.
Parameters
Erebot_Interface_EventHandler $handler Handler that triggered this event.
Erebot_Interface_Event_Event_Numeric $numeric Numeric event indicating that the TLS session was successfully established.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter) (PHPMD.UnusedLocalVariable)
Definition at line 284 of file IrcConnector.php.
References sendCredentials().
Erebot_Module_IrcConnector::sendCredentials () protected
This method sends IRC credentials over the connection. It is called automatically by this module once the connection has been established and the optional security upgrade has been applied to it.
Postcondition
This method sends the proper sequence of PASS (if a password has been configured), NICK and USER commands to the underlying connection. After that, the bot is marked as "registered" from a protocol-oriented point of view.
Note
Even though the underlying connection has been established when this method is called, you SHOULD NOT assume that the bot is connected until an Erebot_Event_Connect event is dispatched.
Definition at line 173 of file IrcConnector.php.
References $_realname.
Referenced by handleLogon(), and handleSTARTTLSSuccess().
Erebot_Module_IrcConnector::setURIFactory ($cls)
Handles a connection to an IRC server. This method is called during the logon phase, right after a TCP connection has been established but before the IRC server accepted us.
Parameters
string $cls Name of a class implementing Erebot_Interface_URI to use to parse Uniform Resource Identifiers.
Definition at line 128 of file IrcConnector.php.
The documentation for this class was generated from the following file:
src/Erebot/Module/IrcConnector.php