Module_Roulette: Erebot\Module\Roulette\Game Class Reference
Erebot\Module\Roulette\Game Class Reference
An implementation of a Russian Roulette game.
Public Member Functions
__construct ($nbChambers)
getChambersCount ()
getPassedChambersCount ()
next ($shooter)
reset ()
setChambersCount ($nbChambers)
Public Attributes
const STATE_BANG = 'bang'
The current chamber contained a bullet.
const STATE_NORMAL = 'normal'
The current chamber was empty.
const STATE_RELOAD = 'reload'
The current chamber was empty and was the last possible empty chamber.
Protected Member Functions
getRandom ($max)
Protected Attributes
$lastShooter
Stores something that identifies the last shooter.
$loadedChamber
Number of the chamber containing the bullet.
$nbChambers
Number of chambers in this gun.
$shotCount
Number of shots fired until now.
Detailed Description
An implementation of a Russian Roulette game.
Definition at line 25 of file Game.php.
Constructor & Destructor Documentation
Erebot\Module\Roulette\Game::__construct ($nbChambers)
Creates a new game of Russian Roulette.
Parameters
int $nbChambers Number of chambers the gun will be made of.
Definition at line 56 of file Game.php.
References Erebot\Module\Roulette\Game\$nbChambers, and Erebot\Module\Roulette\Game\setChambersCount().
Member Function Documentation
Erebot\Module\Roulette\Game::getChambersCount ()
Returns the number of chambers in the gun.
Return values
int Number of chambers in the gun.
Definition at line 143 of file Game.php.
References Erebot\Module\Roulette\Game\$nbChambers.
Erebot\Module\Roulette\Game::getPassedChambersCount ()
Returns the numbers of shots that have already taken place.
Return values
int Current number of shots.
Definition at line 132 of file Game.php.
References Erebot\Module\Roulette\Game\$shotCount.
Erebot\Module\Roulette\Game::getRandom ($max) protected
Returns a random number between 1 and a maximum value (inclusive).
Parameters
int $max Highest value that may be returned by this PRNG.
Return values
int A random value between 1 and $max.
Definition at line 120 of file Game.php.
Referenced by Erebot\Module\Roulette\Game\reset().
Erebot\Module\Roulette\Game::next ($shooter)
Pulls the trigger.
Parameters
mixed $shooter Something that identifies the current shooter. This is used to prevent the same person from shooting twice in a row.
Return values
opaque One of the STATE_* constants, indicating whether a real bullet or an empty chamber was shot.
Exceptions
Erebot_Module_Roulette_TwiceInARowException The same person tried to shoot twice in a row.
Definition at line 76 of file Game.php.
References Erebot\Module\Roulette\Game\reset().
Erebot\Module\Roulette\Game::reset ()
Spins the cylinder.
Definition at line 102 of file Game.php.
References Erebot\Module\Roulette\Game\getRandom().
Referenced by Erebot\Module\Roulette\Game\next(), and Erebot\Module\Roulette\Game\setChambersCount().
Erebot\Module\Roulette\Game::setChambersCount ($nbChambers)
Sets the number of chambers in the gun.
Parameters
int $nbChambers Number of chambers to use for the gun.
Definition at line 154 of file Game.php.
References Erebot\Module\Roulette\Game\$nbChambers, and Erebot\Module\Roulette\Game\reset().
Referenced by Erebot\Module\Roulette\Game\__construct().
The documentation for this class was generated from the following file:
src/Roulette/Game.php