Module_IrcConnector: Erebot\Module\IrcConnector Class Reference
Erebot\Module\IrcConnector Class Reference
Public Member Functions
getBotHostname ()
getBotIdentity ()
getBotNickname ()
getBotRealname ()
getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event,\Erebot\Interfaces\TextWrapper $words)
getNetPassword ()
getURIFactory ()
handleExit (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ExitEvent $event)
handleLogon (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Logon $event)
handleSTARTTLSFailure (\Erebot\Interfaces\NumericHandler $handler,\Erebot\Interfaces\Event\Numeric $numeric)
handleSTARTTLSSuccess (\Erebot\Interfaces\NumericHandler $handler,\Erebot\Interfaces\Event\Numeric $numeric)
reload ($flags)
setURIFactory ($cls)
Protected Member Functions
sendCredentials ()
Protected Attributes
$hostname
Hostname the bot will pretend to be coming from (possibly a fake).
$identity
Identity of the bot on IRC.
$nickname
Nickname to use to connect to the IRC server.
$password
Password of the IRC server.
$realname
The bot's real name on IRC.
$uriFactory = '\\Erebot\\URI'
Class used to parse Uniform Resource Identifiers.
Detailed Description
A module which can send the proper sequence of commands to an IRC server to proceed to the "registered" phase.
This module also supports security upgrades (upgrading from a plain-text connection to a TLS encrypted one) using the STARTTLS extension.
See Also
See http://wiki.inspircd.org/STARTTLS_Documentation for more information on the STARTTLS extension.
Definition at line 33 of file IrcConnector.php.
Member Function Documentation
Erebot\Module\IrcConnector::getBotHostname ()
Returns the bot's hostname.
Return values
string The bot's hostname.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current hostname if it was changed at a later time.
Most IRC servers ignore the hostname announced by clients and do a reverse DNS query on their IP address instead (this is a security measure). The value returned by this method will generally be different from the value used by the server.
Definition at line 379 of file IrcConnector.php.
References Erebot\Module\IrcConnector\$hostname.
Erebot\Module\IrcConnector::getBotIdentity ()
Returns the bot's identity.
Return values
string The bot's ident.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current identity if it was changed at a later time.
Definition at line 355 of file IrcConnector.php.
References Erebot\Module\IrcConnector\$identity.
Erebot\Module\IrcConnector::getBotNickname ()
Returns the bot's nickname.
Return values
string The bot's nickname.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current nickname if it was changed at a later time.
Definition at line 338 of file IrcConnector.php.
References Erebot\Module\IrcConnector\$nickname.
Erebot\Module\IrcConnector::getBotRealname ()
Returns the bot's real name (or GECOS information).
Return values
string The bot's real name.
Note
This is the value defined in the configuration file. It is not updated once the bot is connected, hence, it may be different from the bot's current real name if it was changed at a later time.
Definition at line 396 of file IrcConnector.php.
References Erebot\Module\IrcConnector\$realname.
Erebot\Module\IrcConnector::getNetPassword ()
Returns the password used to connect to this IRC network.
Return values
string The password used to connect to this IRC network.
Note
This method will return an empty string if no password was used to contact this IRC network.
Definition at line 321 of file IrcConnector.php.
References Erebot\Module\IrcConnector\$password.
Erebot\Module\IrcConnector::getURIFactory ()
Handles a connection to an IRC server. This method is called during the logon phase, right after a TCP connection has been established but before the IRC server accepted us.
Return values
string Name of the class used to parse Uniform Resource Identifiers.
Definition at line 138 of file IrcConnector.php.
References Erebot\Module\IrcConnector\$uriFactory.
Erebot\Module\IrcConnector::handleExit (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ExitEvent $event)
Handles an exit request (eg. when the bot receives the SIGTERM signal).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::ExitEvent $event Exit event.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter)
Definition at line 249 of file IrcConnector.php.
Erebot\Module\IrcConnector::handleLogon (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Logon $event)
Handles a connection to an IRC server. This method is called during the logon phase, right after a TCP connection has been established but before the IRC server accepted us.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Logon $event Logon event.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter)
Definition at line 202 of file IrcConnector.php.
References Erebot\Module\IrcConnector\sendCredentials().
Erebot\Module\IrcConnector::handleSTARTTLSFailure (\Erebot\Interfaces\NumericHandler $handler, \Erebot\Interfaces\Event\Numeric $numeric)
Handles a failed TLS session.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Numeric $numeric Numeric event indicating that the TLS session could not be established.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter)
Definition at line 304 of file IrcConnector.php.
Erebot\Module\IrcConnector::handleSTARTTLSSuccess (\Erebot\Interfaces\NumericHandler $handler, \Erebot\Interfaces\Event\Numeric $numeric)
Handles a successful TLS session.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Numeric $numeric Numeric event indicating that the TLS session was successfully established.
Returns
This method does not return anything.
(PHPMD.UnusedFormalParameter) (PHPMD.UnusedLocalVariable)
Definition at line 272 of file IrcConnector.php.
References Erebot\Module\IrcConnector\sendCredentials().
Erebot\Module\IrcConnector::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 65 of file IrcConnector.php.
Erebot\Module\IrcConnector::sendCredentials () protected
This method sends IRC credentials over the connection. It is called automatically by this module once the connection has been established and the optional security upgrade has been applied to it.
Postcondition
This method sends the proper sequence of PASS (if a password has been configured), NICK and USER commands to the underlying connection. After that, the bot is marked as "registered" from a protocol-oriented point of view.
Note
Even though the underlying connection has been established when this method is called, you SHOULD NOT assume that the bot is connected until an Erebot::Event::Connect event is dispatched.
Definition at line 163 of file IrcConnector.php.
References Erebot\Module\IrcConnector\$realname.
Referenced by Erebot\Module\IrcConnector\handleLogon(), and Erebot\Module\IrcConnector\handleSTARTTLSSuccess().
Erebot\Module\IrcConnector::setURIFactory ($cls)
Handles a connection to an IRC server. This method is called during the logon phase, right after a TCP connection has been established but before the IRC server accepted us.
Parameters
string $cls Name of a class implementing Erebot::URIInterface to use to parse Uniform Resource Identifiers.
Definition at line 117 of file IrcConnector.php.
The documentation for this class was generated from the following file:
src/IrcConnector.php