Module_ServerCapabilities: Erebot\Module\ServerCapabilities Class Reference
Erebot\Module\ServerCapabilities Class Reference
A module that can determine what an IRC server is capable of.
Public Member Functions
getCaseMapping ()
getChanLimit ($chanPrefix)
getChanListMode ($list)
getChanModeForPrefix ($prefix)
getChanPrefixForMode ($mode)
getCharset ()
getExtendedBanModes ()
getExtendedBanPrefix ()
getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event,\Erebot\Interfaces\TextWrapper $words)
getIdLength ($prefix)
getMaxListSize ($list)
getMaxParams ()
getMaxTargets ($cmd)
getMaxTextLen ($type)
getMaxVariableModes ()
getNetworkName ()
getSSL ()
handleNumeric (\Erebot\Interfaces\NumericHandler $handler,\Erebot\Interfaces\Event\Numeric $numeric)
hasCommand ($cmdName)
hasExtendedNames ()
hasExtraPenalty ()
hasForcedNickChange ()
hasHybridConnectNotice ()
hasListExtension ($extension)
hasSafeList ()
hasSecureList ()
hasStartTLS ()
hasStatusMsg ($status)
hasUserHostNames ()
isChannel ($chan)
isChannelPrivilege ($mode)
qualifyChannelMode ($mode)
reload ($flags)
supportsStandard ($standard)
Public Attributes
const ELIST_CREATION = 'C'
ELIST mode for creation time search.
const ELIST_MASK = 'M'
ELIST mode for a mask search.
const ELIST_NEG_MASK = 'N'
ELIST mode for a negative mask search.
const ELIST_TOPIC = 'T'
ELIST mode for topic search.
const ELIST_USERS = 'U'
ELIST mode for usercount search.
const LIST_BANS = 0
Refers to the list of bans.
const LIST_EXCEPTS = 2
Refers to the list of ban exceptions.
const LIST_INVITES = 3
Refers to the list of invitations.
const LIST_SILENCES = 1
Refers to the list of silenced persons.
const LIST_WATCHES = 4
Refers to the list of watched persons.
const MODE_TYPE_A = 0
Refers to modes that add or remove a nick or address to a list.
const MODE_TYPE_B = 1
Refers to modes that change a setting and always have a parameter.
const MODE_TYPE_C = 2
const MODE_TYPE_D = 3
Refers to modes that change a setting and never have a parameter.
const PATTERN_PREFIX = '/^\\(([^\\)]+)\\)(.*)$/'
Pattern for a prefix-to-mode mapping.
const TEXT_AWAY = 4
Refers to away messages.
const TEXT_CHAN_NAME = 0
Refers to channel names.
const TEXT_KICK = 3
Refers to kick messages.
const TEXT_NICKNAME = 1
Refers to nicknames.
const TEXT_TOPIC = 2
Refers to channel topics.
Protected Member Functions
parseToken ($token)
Protected Attributes
$parsed
Whether server capabilities have been parsed yet or not.
$supported
Modes/commands/exteions/options supported by this IRC server.
Detailed Description
A module that can determine what an IRC server is capable of.
Definition at line 26 of file ServerCapabilities.php.
Member Function Documentation
Erebot\Module\ServerCapabilities::getCaseMapping ()
Returns the name of the case mapping currently used by the server.
Return values
string The mapping in use. If this information is not available, this method assumes the mapping defined in RFC 1459 ("rfc1459") is used.
Definition at line 797 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getChanLimit ($chanPrefix)
Returns the maximum number of channels of a given type that you may join simultaneously.
Parameters
string $chanPrefix The type of channel to query, given by its prefix (eg. "#" or "&").
Return values
int The number of channels of this type that you may be on simultaneously or -1 if there is no such limit.
Exceptions
Erebot::InvalidValueException The given $chanPrefix does not refer to a valid channel type.
Note
Even if this method returns -1 for a given type, you should always assume that the server uses an implicit limit (sometimes as low as 10).
Definition at line 687 of file ServerCapabilities.php.
References Erebot\Module\ServerCapabilities\isChannel().
Erebot\Module\ServerCapabilities::getChanListMode ($list)
Returns the channel mode to use to retrieve the content of a channel list of a certain type.
Parameters
opaque $list The type of list to query, expressed using one of the LIST_* constants of this class.
Return values
string The channel mode to query to retrieve the content of the list represented by $list.
Exceptions
Erebot::InvalidValueException There is no such type of list.
Erebot::NotFoundException The given type of list is not available on that particular IRC server.
Definition at line 871 of file ServerCapabilities.php.
Referenced by Erebot\Module\ServerCapabilities\getMaxListSize().
Erebot\Module\ServerCapabilities::getChanModeForPrefix ($prefix)
Returns the channel mode associated with a given prefix (eg. 'v' for voices [+] and 'o' for operators [@]).
Parameters
string $prefix The prefix for which the corresponding channel mode must be returned.
Return values
string The mode corresponding to that prefix.
Exceptions
Erebot::InvalidValueException The given $prefix is not valid.
Erebot::NotFoundException The given $prefix does not refer to a channel status.
See Also
Erebot::Module::ServerCapabilities::getChanPrefixForMode() does the opposite translation.
Definition at line 1037 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getChanPrefixForMode ($mode)
Returns the prefix associated with a given channel mode representing a specific status (eg. '+' for voices [v] and '@' for operators [o]).
Parameters
string $mode The channel mode for which the corresponding prefix must be returned.
Return values
string The prefix corresponding to that mode.
Exceptions
Erebot::InvalidValueException The given $mode is not valid.
Erebot::NotFoundException The given $mode does not refer to a channel status.
See Also
Erebot::Module::ServerCapabilities::getChanModeForPrefix() does the opposite translation.
Definition at line 982 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getCharset ()
Returns the charset used by this IRC server.
Return values
string The server's charset.
Exceptions
Erebot::NotFoundException The server did not declare its charset.
Definition at line 814 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getExtendedBanModes ()
Returns the list of extended bans implemented by this IRC server.
Return values
list List of extended bans supported by this server.
Exceptions
Erebot::NotFoundException This IRC server does not support extended bans.
Definition at line 1410 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getExtendedBanPrefix ()
Returns the prefix used to modify or query the list of the extended bans.
Return values
string The prefix to use to manipulate extended bans.
Exceptions
Erebot::NotFoundException This IRC server does not support extended bans.
Definition at line 1384 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event, \Erebot\Interfaces\TextWrapper $words)
Provides help about this module.
Parameters
Erebot::Interfaces::Event::Base::TextMessage $event Some help request.
Erebot::Interfaces::TextWrapper $words Parameters passed with the request. This is the same as this module's name when help is requested on the module itself (in opposition with help on a specific command provided by the module).
Definition at line 149 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getIdLength ($prefix)
Returns the length of the "id" portion of "safe" channels of a given type.
Parameters
string $prefix The type of channel, represented by its prefix.
Return values
int The length of the "id" portion of safe channels.
Exceptions
Erebot::InvalidValueException The given $prefix does not represent a valid channel type.
Erebot::NotFoundException Safe channels are not supported by this IRC server.
Definition at line 1293 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getMaxListSize ($list)
Returns the maximum number of entries a list may contain.
Parameters
opaque $list One of the LIST_* constants, representing the type of list for which this information must be retrieved.
Return values
mixed Returns the number of entries this type of list may contain or null if no maximum has been defined.
Exceptions
Erebot::InvalidValueException The value passed to $list does not represent a valid list type.
Note
Even if the server does not specify a maximum number of entries for some list, you should always assume that the server has an implicit value for it, which is usually not that high (like 30 entries or so).
On some servers, several lists are managed together hence the value returned by this method represents the maximum number of entries these shared lists may occupy and not the individual capacity of these lists.
Definition at line 621 of file ServerCapabilities.php.
References Erebot\Module\ServerCapabilities\getChanListMode().
Erebot\Module\ServerCapabilities::getMaxParams ()
Returns the maximum number of parameters that may be passed to any command.
Return values
int Maximum number of parameters to any command.
Note
This value will generally be 12, which is what RFC 1459 defines, but may also be set to an higher value as IRC servers are now capable of processing more complex messages.
Definition at line 1212 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getMaxTargets ($cmd)
Returns the maximum number of targets (nickname or channel) a given command may accept.
Parameters
string $cmd The command to query.
Return values
int The maximum number of targets for that command or -1 if there is no limit or it is unknown.
Exceptions
Erebot::InvalidValueException::$cmd does not refer to a valid IRC command.
Note
Even if this method returns -1, you should always assumre that the IRC server uses an implicit limit.
Even if the server accepts a large number of simultaneous targets, the maximum size of the command must still comply with other limits defined by the server and the various standards (eg. RFC 1459 imposes a maximum length of 1024 bytes for every message sent, including the trailing CR LF sequence).
Definition at line 1146 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getMaxTextLen ($type)
Returns the maximum size messages/entities of a given type may occupy.
Parameters
opaque $type The type of message/entity to test, expressed using one of the TEXT_* constants of this class.
Return values
int The maximum size for a message/entity of type $type or -1 if there is no limit (or the limit is unknown).
Exceptions
Erebot::InvalidValueException The given $type does not refer to a valid type of message/entity.
Note
Even if this method returns -1, you should always assume that an implicit limit exists (whose value still depends on the type). For example, the original Request for Comments on IRC (RFC 1459) specifies that nicknames may not exceed 9 characters in length.
Definition at line 738 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getMaxVariableModes ()
Returns the maximum number of channel modes that may be changed at once.
Return values
int The maximum number of channel modes of any type that can be changed at once.
Note
For historical reasons, a value of 3 is assumed for IRC servers that do not specify a limit.
Definition at line 1184 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getNetworkName ()
The IRC network this server belongs to.
Return values
string Name of the IRC network this server belongs to.
Exceptions
Erebot::NotFoundException The server did not declare itself as being part of any specific IRC network.
Warning
The name returned by this method is purely informative. The server is free to send any name it chooses. Don't rely on this to implement security checks!
Definition at line 841 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::getSSL ()
Indicates whether this server support SSL connections.
Return values
dict An associative array whose keys are the IP addresses and whose values are the port where SSL support is enabled.
Exceptions
Erebot::InvalidValueException The data received from the IRC server was invalid.
Erebot::NotFoundException No information could be retrieved indicating whether this IRC server supports SSL connections or not.
Note
When SSL is supported on all IPs for a given port, the IP (the key) is defined as "*".
Definition at line 1239 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::handleNumeric (\Erebot\Interfaces\NumericHandler $handler, \Erebot\Interfaces\Event\Numeric $numeric)
Handles numeric events.
Parameters
Erebot::Interfaces::NumericHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Numeric $numeric The numeric event to handle.
(PHPMD.UnusedFormalParameter)
Definition at line 182 of file ServerCapabilities.php.
References Erebot\Module\ServerCapabilities\$supported, and Erebot\Module\ServerCapabilities\parseToken().
Erebot\Module\ServerCapabilities::hasCommand ($cmdName)
Indicates whether a particular command is supported or not.
Parameters
string $cmdName Name of the command whose support must be tested.
Return values
bool true if the given command is supported, false otherwise.
Exceptions
Erebot::InvalidValueException The given $cmdName is not a valid command name.
Note
This method only exists to test support for commands which are not yet widely recognized by IRC clients. Basic commands such as those described in RFC 1459 and its successors need not be tested (this method will indeed return false for such commands).
Many commands actually have separate methods to check for their support. This is a limitation of the current implementation. Those methods will probably be merged in hasCommand() later on.
Definition at line 407 of file ServerCapabilities.php.
References Erebot\Module\ServerCapabilities\supportsStandard().
Erebot\Module\ServerCapabilities::hasExtendedNames ()
Whether extended names are supported by this server. Extended names make it possible to retrieve all modes set for a particular user on a channel using the /NAMES command. This extension is disabled by default and must be explicitly enabled by sending a "PROTOCTL NAMESX" message to the server. When this extension is disabled, the server will only send the highest mode of each user in reply to /NAMES.
Return values
bool true if the server supports the NAMESX extension, false otherwise.
Definition at line 307 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasExtraPenalty ()
Indicates whether the server gives extra penalty to some commands instead of the normal 2 seconds per message and 1 second for every 120 bytes in a message.
Return values
bool true if the server gives extra penalty for certain commands, false otherwise.
Definition at line 342 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasForcedNickChange ()
Indicates whether the server may change the bot's nickname on its own.
Return values
bool true if the server may choose to change a user's nickname at its own discretion, false otherwise.
Definition at line 355 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasHybridConnectNotice ()
Whether the server supports the Hybrid Connect Notice extension. This extension is aimed at IRC operators and (more likely) IRC services. The Hybrid Connect Notice (HCN) slightly changes the format used by connection notices so that it matches the format expected by the Blitzed Open Proxy Monitor (http://wiki.blitzed.org/BOPM). This includes displaying the user's IP address in connect/exit notices.
Return values
bool true if the server supports the HCN extension, false otherwise.
Definition at line 374 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasListExtension ($extension)
Whether the server supports extensions for the LIST command or not. Extended LIST allows one to search channels not only by their name but also using other criteria such as their topic, creation time, user count, etc.
Parameters
opaque $extension The extension for which support must be tested. Use the Erebot::Module::ServerCapabilities::ELIST_* series of constant for this parameter.
Return values
bool true if the given $extension is supported, false otherwise.
Definition at line 281 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasSafeList ()
Indicates whether replies to a LIST command will be sent in multiple iterations to avoid the send queue to overflow.
Return values
bool true if replies to LIST commands may be split in several messages, false otherwise.
Definition at line 453 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasSecureList ()
Indicates whether the server may deny requests to send channel lists until the bot has been connected for long enough.
Return values
bool true if the server may deny access to channel lists until a certain amount of time has been spent connected, false otherwise.
Definition at line 468 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasStartTLS ()
Whether the server supports the STARTTLS command. This is only an indication so that clients using a plain-text connection may choose to disconnect and reconnect using a TLS encrypted connection.
Return values
bool true if the server support TLS encrypted connections, false otherwise.
Definition at line 483 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasStatusMsg ($status)
Indicates whether a message can be sent in a channel so that only users with a specific status will receive it.
Parameters
string $status A status prefix for which this ability must be tested.
Return values
bool Indicates that the given status prefix
Note
Nowadays, most IRC servers support at least this features for the '+', '' & '@' status prefixes, meant to send messages to voices only, halfops only & operators only (respectively).
Depending on the IRC server, the exact command to use to send messages to users with a specific status may vary. In particular, on some servers you'll need to use dedicated commands, like WALLCHOPS or WALLVOICES.
Definition at line 510 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::hasUserHostNames ()
Whether the server can send full the user!ident@host in a reply to a NAMES command. This makes it possible to build an internal list of addresses without requiring an extra /WHO or /WHOIS command. This extension is disabled by default and must be explicitly enabled by sending a "PROTOCTL UHNAMES" message to the server. When this extension is disabled, the server will only send the user's nickname in reply to /NAMES.
Return values
bool true if the server supports the UHNAMES extension, false otherwise.
Definition at line 327 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::isChannel ($chan)
Checks whether a given string contains a valid channel name.
Parameters
string $chan Potential channel name to test.
Return values
bool true if the given $chan can be used as a channel name, false otherwise.
Note
This method uses very basic checks to test validity of the $chan as a channel name. Therefore, a server may reject a channel name which was recognized as being valid by this method.
Definition at line 552 of file ServerCapabilities.php.
Referenced by Erebot\Module\ServerCapabilities\getChanLimit().
Erebot\Module\ServerCapabilities::isChannelPrivilege ($mode)
Indicates whether the given mode is a valid channel privilege (such as "o" or "v") or not.
Parameters
string $mode The channel mode to test.
Return values
bool true if the given mode can be used as a valid channel privilege, false otherwise.
Definition at line 932 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::parseToken ($token) protected
Parses a token from the 005 numeric event.
Parameters
string $token A token from the 005 numeric event.
Return values
array Result of the parsing.
Definition at line 223 of file ServerCapabilities.php.
Referenced by Erebot\Module\ServerCapabilities\handleNumeric().
Erebot\Module\ServerCapabilities::qualifyChannelMode ($mode)
Returns the type of mode a given channel mode belongs to, using the classification method defined in RFC 1459.
Parameters
string $mode The channel mode to qualify.
Return values
opaque One of the MODE_TYPE_* constants defined in this class, indicating whether the given $mode is of type A, B, C or D.
Exceptions
Erebot::InvalidValueException The given parameter does not refer to a valid channel mode.
Erebot::NotFoundException The given $mode does not exist on this IRC server.
Definition at line 1089 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 111 of file ServerCapabilities.php.
Erebot\Module\ServerCapabilities::supportsStandard ($standard)
Indicates whether this IRC server supports a specific standard.
Parameters
string $standard The name of the standard for which support must be tested.
Return values
bool true if the IRC server supports that $standard, false otherwise.
Exceptions
Erebot::InvalidValueException The given $standard does not a refer to a valid standard.
Note
Values returned by this method are purely informational. An IRC server may choose to not advise support for standards it recognized. It may also advise support for a standard while it only partially implements it.
Definition at line 1342 of file ServerCapabilities.php.
Referenced by Erebot\Module\ServerCapabilities\hasCommand().
Member Data Documentation
const Erebot\Module\ServerCapabilities::MODE_TYPE_C = 2
Refers to modes that change a setting and only have a parameter when set.
Definition at line 68 of file ServerCapabilities.php.
The documentation for this class was generated from the following file:
src/ServerCapabilities.php